### ISSUE TITLE
[Bug] [UI] Unable to edit timing management 

### ISSUE THREAD

**Issue by littleziao** [apache/dolphinscheduler#10087] opened 2022-05-18 03:35 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When editing the cron manage of the workflow, when selecting a specific number of hours (equivalent to seconds, minutes, etc.), the drop-down menu of the selection box cannot be selected and disappears quickly.

![image](https://user-images.githubusercontent.com/56712269/168951012-31ca7ef3-6ee7-4947-8883-02bc0ce65609.png)

After I checked with Slack, they told me his was available

### What you expected to happen

cron manage can be edited.

### How to reproduce

Workflow Definition -> cron manage -> edit -> Timing  -> Specific second(multiple) 
![微信截图_20220518113513](https://user-images.githubusercontent.com/56712269/168951992-85242a5d-0173-4a4b-b0f7-1580074dfe80.png)

### Version

3.0.0-alpha standalone-server

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by littleziao** [comment] 2022-05-18 09:23
Do you have a release date for beta? We want to use 3.0.0 in production.

**Comment by zhongjiajie** [comment] 2022-05-23 09:25
@littleziao  I have tested it in my env with 3.0.0-beta branch and it work fine

**Comment by zhongjiajie** [comment] 2022-05-24 06:50
@songjianet I find out it still exists in 3.0.0-beta-1 
![bug-scheduler-workflow](https://user-images.githubusercontent.com/15820530/169966717-8d25e93c-6e4a-4928-a6e1-439083864eb1.gif)

**Comment by zhongjiajie** [comment] 2022-05-24 06:50
But maybe we could fix it in 3.0.0-beta-2, WDYT

**Comment by songjianet** [comment] 2022-05-24 06:53
![image](https://user-images.githubusercontent.com/19239641/169967365-c4d73379-e7bd-4784-bd74-d23825f0395a.png)
I thought my brother was going to fix it.

**Comment by littleziao** [comment] 2022-05-24 06:54
This problem did not occur when I ran the front-end project locally, only on the server. I also tried to replace the UI package on the server, but it did not work

**Comment by songjianet** [comment] 2022-05-24 06:55
> This problem did not occur when I ran the front-end project locally, only on the server. I also tried to replace the UI package on the server, but it did not work

That may require the help of the back-end friends to look at it.

**Comment by devosend** [comment] 2022-05-24 06:57
> @songjianet I find out it still exists in 3.0.0-beta-1 ![bug-scheduler-workflow](https://user-images.githubusercontent.com/15820530/169966717-8d25e93c-6e4a-4928-a6e1-439083864eb1.gif) [ ](https://user-images.githubusercontent.com/15820530/169966717-8d25e93c-6e4a-4928-a6e1-439083864eb1.gif) ![bug-scheduler-workflow](https://user-images.githubusercontent.com/15820530/169966717-8d25e93c-6e4a-4928-a6e1-439083864eb1.gif) [ ](https://user-images.githubusercontent.com/15820530/169966717-8d25e93c-6e4a-4928-a6e1-439083864eb1.gif)

This is not a bug. Beause you not select `Specific hour(multiple)` when you edit hour

**Comment by zhongjiajie** [comment] 2022-05-24 07:05
> 

I change the milestone to `3.0.0-beta-2` maybe we should auto-select the bottom `specifich hour` when users change the detail value about scheduler time, WDYT

**Comment by littleziao** [comment] 2022-05-24 07:06
![LAPTOP-NEPPVNGC-2022-05-24-15-00-29_Trim](https://user-images.githubusercontent.com/56712269/169969528-e19751c5-e633-4396-ab78-93d45490d7b9.gif)
I tried, but it was still there

**Comment by devosend** [comment] 2022-05-24 07:07
Can you try chrome?

**Comment by littleziao** [comment] 2022-05-24 07:08
ok，i will try

**Comment by littleziao** [comment] 2022-05-24 07:09
In Chrome, it still exists

**Comment by zhongjiajie** [comment] 2022-05-25 04:00
> In Chrome, it still exists

It is not exists in my env

**Comment by littleziao** [comment] 2022-05-25 06:12
So I don't know if it was a front end problem or a back end problem or something in my env when I was deploying, but I don't think it was a deployment problem that caused this odd phenomenon,WDYT

**Comment by zhongjiajie** [comment] 2022-05-30 07:20
> So I don't know if it was a front end problem or a back end problem or something in my env when I was deploying, but I don't think it was a deployment problem that caused this odd phenomenon,WDYT

could you upgrade your google chrome to the latest version and try again? @littleziao

**Comment by littleziao** [comment] 2022-06-06 02:26
my chrome is constantly updated, and it was the latest version when I tested it. 
sry, last week i didn't reply in time cause had something with myself.

**Comment by zhongjiajie** [comment] 2022-06-06 02:38
> my chrome is constantly updated, and it was the latest version when I tested it.
> sry, last week i didn't reply in time cause had something with myself.

In this case, maybe there is a bug in version 3.0.0-alpha, but we tests both 3.0.0-beta-1 and dev, it is ok

**Comment by littleziao** [comment] 2022-06-06 02:41
I used 2.0.5 for production and i will upgrade 3.0.0-beta if the time is right

**Comment by littleziao** [comment] 2022-06-06 02:42
thinks

**Comment by zhongjiajie** [comment] 2022-06-06 02:46
> I used 2.0.5 for production and i will upgrade 3.0.0-beta if the time is right

Got it, so I prefer to close this issue in this case, you could reopen it if you find it still exists in 3.0.0-beta-1 or other latest release

**Closed as completed by zhongjiajie** 2022-06-06 02:46 UTC
Labels: bug, wontfix, backend
