### ISSUE TITLE
Deploy kubernetes according to the official website document, failed!

### ISSUE THREAD

**Issue by ChenpiDog** [apache/dolphinscheduler#10400] opened 2022-06-10 06:30 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the official documents of 2.0.5 and 3.0.0-beta-1, there are problems in the deployment of kubernetes. The deployment cannot succeed according to the instructions in the documents.

Encountered the following problems:

1) Execute "helm dependency update." "Error: can't get a valid version for repositories PostgreSQL, zookeeper. try changing the version constraint in chart.yaml". Set chart In yaml, the PostgreSQL version is changed to 11.0.0, and the zookeeper version is changed to 9.0.0. This step can be successful.

2) After "helm install dolphin scheduler. --set image.tag=2.0.5" is executed, the status of pod is createcontainerconfigerror, and the error message of pod is: "error: could't find key PostgreSQL password in secret default/dolphin scheduler PostgreSQL". Check the secret. There is PostgreSQL password in the secret.

### What you expected to happen

I hope the application can be successfully deployed according to the official website documents, but there are many problems.

### How to reproduce

Just follow the official website documents to reproduce the problem.

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment] 2022-06-15 07:30
I hope the official can update the deployment document on the official website as soon as possible.

**Comment by qingwli** [comment] 2022-06-22 03:15
I have checked version 300b1 and they do have this bug. 

- Question one has been fixed by  #10419. It looks like `bitnami repo` has updated `postgresql` and `zookeeper` versions. And they don't contains the low version. 

I think is a huge problem. When DS release a new version, the `postgresql` and `zookeeper` version will be specified and not changed anymore. And the people who want to deploy on K8s will occur this problem.

- Question two is still on 300b1 and I'm not sure is fixed by the dev or not. I'll check later. And looks like `postgresql` upgraded to a high version and needs some code changes.

**Comment by qingwli** [comment] 2022-06-22 06:03
- Due `postgresql` upgrade and  postgresql-password has been changed. See  https://github.com/bitnami/charts/commit/50946fdff3d90522d0b87012f8b9bb73c4b6f12c#diff-00f2e1e3c249371477aae086aa0c058d3e8e34d7045398f5d558d34840cef2e1R16-R22

I'll open a PR to fix question 2.

**Comment by qingwli** [comment] 2022-06-22 06:33
- #10419 && #10545 need to cherry-pick to verison 2.0.6 and 300b2 @zhongjiajie

**Comment by qingwli** [comment] 2022-06-23 02:58
PTAL this issue @kezhenxu94 , the `bitnami repo` question has a high impact

**Comment by qingwli** [comment] 2022-06-23 05:39
Upgrade `postgresql` and `zookeeper` `bitnami ` versions will occur other problems. It needs check and tested.

And I found the root cause is [here](https://github.com/bitnami/charts/issues/10539), so we just need to update the repo URL and not do anything else.

I'll open a PR to fix this problem, including recovering the versions and the PostgreSQL key name.

Maybe later to upgrade the versions.

And another question. This bug will impact all versions that supported K8s deployed. How about we update the docs on the official website as soon as possible? We add a note to tell the users to change the `bitnami repo` may be like this:

```
Change deploy/kubernetes/dolphinscheduler/Chart.yaml at line 47 && 51

-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
```

WDYT @zhongjiajie

**Comment by zhongjiajie** [comment] 2022-06-23 06:11
> Upgrade `postgresql` and `zookeeper` `bitnami ` versions will occur other problems. It needs check and tested.
> 
> And I found the root cause is [here](https://github.com/bitnami/charts/issues/10539), so we just need to update the repo URL and not do anything else.
> 
> I'll open a PR to fix this problem, including recovering the versions and the PostgreSQL key name.
> 
> Maybe later to upgrade the versions.
> 
> And another question. This bug will impact all versions that supported K8s deployed. How about we update the docs on the official website as soon as possible? We add a note to tell the users to change the `bitnami repo` may be like this:
> 
> ```
> Change deploy/kubernetes/dolphinscheduler/Chart.yaml at line 47 && 51
> 
> -   repository: https://charts.bitnami.com/bitnami
> +   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
> ```
> 
> WDYT @zhongjiajie

sounds good to me, WDYT @kezhenxu94

**Comment by kezhenxu94** [comment] 2022-06-23 06:57
We can add the notes to docs of previous releases if that is practical

**Closed as completed** 2022-06-24 07:29 UTC
Labels: bug, help wanted, backend
