### ISSUE TITLE
[Bug] [Worker] TaskInstance state update error

### ISSUE THREAD

**Issue by guoshupei** [apache/dolphinscheduler#10608] opened 2022-06-24 16:59 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

find version: 2.0.1

When TaskExecuteThread  is running, if an exception is threw, it is caught and the kill method is executed,  but if kill methond also throw error instead of an exception, the `TaskExecuteResponseCommand` can not be set properties, like status, endTime, these can be set default value, for example, the `status` can be set 0 (state of `submit success`)

- log
![image](https://user-images.githubusercontent.com/29919212/175577732-ac95b6f2-2114-4e0b-bb99-ddb46ebabb10.png)

- code
![image](https://user-images.githubusercontent.com/29919212/175606777-81fa9d9f-9acd-444b-9659-07a2818c2a9e.png)

### What you expected to happen

The state of TaskInstance is correct

### How to reproduce

- 1. throw `exception/error `in try block
- 2. throw `error `in kill methond

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment] 2022-06-25 02:57
I see the code in 2.0.5, the `kill` method will never throw exception. So this should already be fixed, I will close this issue.

**Comment by guoshupei** [comment] 2022-06-25 03:23
@ruanwenjun not exception, but error. the user can custom task plugins, so override can be throw error , this happened with our custom Linkis plugin

**Comment by guoshupei** [comment] 2022-06-25 03:25
@ruanwenjun And if you look at my screenshot, although it's exception, it's actually reversed.

**Comment by ruanwenjun** [comment] 2022-06-25 06:08
@guoshupei Ok, so it's better to move the setting part to finally. Could you please submit a PR to fix this?

**Comment by guoshupei** [comment] 2022-06-25 07:26
> 



> @guoshupei Ok, so it's better to move the setting part to finally. Could you please submit a PR to fix this?

yes ,  as you said, I need to know the task execution to set different states, failure or success.
but I have another plan:
- First, put `kill()` after setting part, 
- Second, replace `Exception` with `Throwable` of `catch` block in `kill` method 

WDYT?

**Comment by ruanwenjun** [comment] 2022-06-25 07:28
> > 
> 
> > @guoshupei Ok, so it's better to move the setting part to finally. Could you please submit a PR to fix this?
> 
> yes , as you said, I need to know the task execution to set different states, failure or success. but I have another plan:
> 
> * First, put `kill()` after setting part,
> * Second, replace `Exception` with `Throwable` of `catch` block in `kill` method
> 
> WDYT?

The first plan looks good to me.

**Comment by guoshupei** [comment] 2022-06-25 07:47
> > > 
> > 
> > 
> > > @guoshupei Ok, so it's better to move the setting part to finally. Could you please submit a PR to fix this?
> > 
> > 
> > yes , as you said, I need to know the task execution to set different states, failure or success. but I have another plan:
> > 
> > * First, put `kill()` after setting part,
> > * Second, replace `Exception` with `Throwable` of `catch` block in `kill` method
> > 
> > WDYT?
> 
> The first plan looks good to me.

okay，I will use first plan to fix it.

**Comment by brave-lee** [comment] 2022-09-27 06:02
@guoshupei Can 2.0.6 version be reproduced ？

**Comment by guoshupei** [comment] 2022-09-27 07:36
> @guoshupei Can 2.0.6 version be reproduced ？

I don't use the 2.0.6 version, but I think it still exists

**Comment by guoshupei** [comment] 2022-09-27 07:50
> @guoshupei Can 2.0.6 version be reproduced ？
@JinyLeeChina Here's how we do it

![image](https://user-images.githubusercontent.com/29919212/192465855-e8110d00-41e6-4e02-80da-ec6015ed120c.png)
![image](https://user-images.githubusercontent.com/29919212/192466087-d0a17ea7-fbbf-4735-8663-c0830fab214d.png)

**Comment by brave-lee** [comment] 2023-01-12 12:18
The reason is the same as #13244

**Closed as completed by brave-lee** 2023-01-12 12:18 UTC
Labels: bug, backend
