### ISSUE TITLE
[Bug][api] select an existing tenant, the workflow fails to run, indicating that the tenant does not exist

### ISSUE THREAD

**Issue by xingchun-chen** [apache/dolphinscheduler#4995] opened 2021-03-07 12:25 UTC
![image](https://user-images.githubusercontent.com/55787491/110239702-40d3d580-7f83-11eb-8cb9-14f0110ac478.png)
![image](https://user-images.githubusercontent.com/55787491/110239708-47fae380-7f83-11eb-8c43-5435143e5c7b.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by CalvinKirs** [comment] 2021-03-08 14:07
This is not a bug, you can refer to the email discussion: https://lists.apache.org/thread.html/ra44b2e69759fcc980e4ed04c1811037bf0e743e47827fc2dcd1049d6%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by CalvinKirs** [comment] 2021-03-12 16:33
As I said, this is not a bug. If you need to implement this feature, you can discuss it at #5006. I will close it.

**Closed as completed by CalvinKirs** 2021-03-12 16:33 UTC
