### ISSUE TITLE
[Feature] Support refer existed task definition to create a workflow definition

### ISSUE THREAD

**Issue by TCGOGOGO** [apache/dolphinscheduler#14038] opened 2023-04-28 07:58 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For several common tasks, there is no way to re-use them simply when create a new workflow definition, we have to wrap such task inside a new workflow and used as a subprocess or just copy it manaully.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment] 2023-04-29 14:48
Duplicate of https://github.com/apache/dolphinscheduler/issues/13513

**Closed as completed** 2023-05-03 15:09 UTC
Labels: duplicate, feature, Waiting for reply
