### ISSUE TITLE
[Bug] [Master] Force Success Invalid

### ISSUE THREAD

**Issue by Thomas-HuWei** [apache/dolphinscheduler#15849] opened 2024-04-15 11:41 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In newest version 3.2.1, force success has invalid.
When master run one step of instance failed, I set the step to force success, but next time, this step run again and it's old record already been set to failure status.

![image](https://github.com/apache/dolphinscheduler/assets/99788018/9181eb65-74ef-44c1-b8cd-449342ddb3f0)

I've search the code, find in file https://github.com/apache/dolphinscheduler/blob/3.2.1-release/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
![image](https://github.com/apache/dolphinscheduler/assets/99788018/17d163c6-701f-4598-b181-733d6eaced73)

In this position, you will update taskInstance in DB using your memory old data, that means when I use api to force success, the db record is changed, but next time here you override db state(13-force success) by your memory old state(6-fail).

And then I fix the record status, but the function force success is can't still work. There must be other bugs.

### What you expected to happen

Force success can work successfully!

### How to reproduce

Easy to produce, use the 3.2.1 version to deploy, and test force success function, it will must reproduce again.

### Version

3.2.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment] 2024-04-16 01:57
Thanks for reporting this, I will fix this.

**Comment by Thomas-HuWei** [comment] 2024-04-16 02:17
We have been using ds2. It's time to get stuck. Can you give me an approximate repair time? We don't depend on the release version. With a commit, we can cherry pick it into our fork warehouse.

**Comment by ruanwenjun** [comment] 2024-04-16 02:50
> We have been using ds2. It's time to get stuck. Can you give me an approximate repair time? We don't depend on the release version. With a commit, we can cherry pick it into our fork warehouse.

In the original design, the `force success` button can only execute at task instance in which workflow instance is finished.
So the hot fix is only add a status restriction.

I am not sure if this is suitable for you requirement. If you want to force success a running workflow instance this should be a new feature not a bug, since the  runtime operation should have a new design.

**Comment by Thomas-HuWei** [comment] 2024-04-16 03:31
> > We have been using ds2. It's time to get stuck. Can you give me an approximate repair time? We don't depend on the release version. With a commit, we can cherry pick it into our fork warehouse.
> 
> In the original design, the `force success` button can only execute at task instance in which workflow instance is finished. So the hot fix is only add a status restriction.
> 
> I am not sure if this is suitable for you requirement. If you want to force success a running workflow instance this should be a new feature not a bug, since the runtime operation should have a new design.

No. In ds2.x, if  a process instance has three step, a->b->c， and all of them has 5 retry times.
When b must fail,  then I return the whole instance, and b still fail, and need retry at least 5 times.
Now the instance is still running, then I set the b step to force success, next retry time, b will be skip, and c will run.

But In ds3.2.1,  this operation is invalid, I can't set b step to force success to skip and let c to run.
Why not  I use "run after b" to instead of force success b (means skip b), because DAG may be parallel and complex, can skip this step is the best chorice.

**Comment by Thomas-HuWei** [comment] 2024-04-16 03:41
ds2:
1.Running：
![image](https://github.com/apache/dolphinscheduler/assets/99788018/f21c2dee-c127-40bd-a8bb-f23acaeb31e6)

2. force success step b, and the instance is stilling running!
![image](https://github.com/apache/dolphinscheduler/assets/99788018/9586a3ec-911a-4eaf-9932-1d363da1a8fc)
![image](https://github.com/apache/dolphinscheduler/assets/99788018/aa53ff86-1fc7-40d3-a066-ff6d1cab0a82)


3. next time run：will skip b and run c, and the instance is success.
![image](https://github.com/apache/dolphinscheduler/assets/99788018/874e789b-9e05-4007-a8c0-c34d3e7b6e9a)
![image](https://github.com/apache/dolphinscheduler/assets/99788018/2a4ea206-68ad-47b6-8dca-1761fc11d3fe)


here is my test wfs,but this operation in ds3.2.1, force success b, can't skip b, next time, it will run fail again.

[skip_test.json](https://github.com/apache/dolphinscheduler/files/14986517/skip_test.json)

**Comment by ruanwenjun** [comment] 2024-04-16 03:50
> ds2: 1.Running： ![image](https://private-user-images.githubusercontent.com/99788018/322693078-f21c2dee-c127-40bd-a8bb-f23acaeb31e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk1NTUsIm5iZiI6MTcxMzIzOTI1NSwicGF0aCI6Ii85OTc4ODAxOC8zMjI2OTMwNzgtZjIxYzJkZWUtYzEyNy00MGJkLWE4YmItZjIzYWNhZWIzMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZDc3MTYxNmFkMjZiZjNmNDU5ZDEyN2FjYWQ5NzAxY2EwY2I4NTM2NTU3OTdjMmNlMWU1ZTJmYzdmNDZhMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPHGlQ_2HMvAm71Aa9iBsOghlNNu-5dijx-QsAGj-Ow)
> 
> 2. force success step b, and the instance is stilling running!
>    ![image](https://private-user-images.githubusercontent.com/99788018/322693161-9586a3ec-911a-4eaf-9932-1d363da1a8fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk1NTUsIm5iZiI6MTcxMzIzOTI1NSwicGF0aCI6Ii85OTc4ODAxOC8zMjI2OTMxNjEtOTU4NmEzZWMtOTExYS00ZWFmLTk5MzItMWQzNjNkYTFhOGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZWYyZWQ0NjYxMmIzYzQ2ZWY5ZGM2OTE1YmUyNmFmMTNhYjQzNGM2YzcyZGNmMTllYWE4ZTQyMTkwN2JhOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HYmi-6mV87XkGv1wHXFARhu3sFqGF0NUkk4Pbkc2nE4)
>    ![image](https://private-user-images.githubusercontent.com/99788018/322693275-aa53ff86-1fc7-40d3-a066-ff6d1cab0a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk1NTUsIm5iZiI6MTcxMzIzOTI1NSwicGF0aCI6Ii85OTc4ODAxOC8zMjI2OTMyNzUtYWE1M2ZmODYtMWZjNy00MGQzLWEwNjYtZmY2ZDFjYWIwYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmVmYTBmZGY5M2M2MGYxNTgyYzUzNGRmYTQ4NjQxZTk2OTIyNzU1MGNlM2I1MDI2Nzk1OGNlOTZjNDVhZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESG9z51ze1kdiPwh9IvOfNNDUy42J4kqrc2XgP04tDw)
> 3. next time run：will skip b and run c, and the instance is success.
>    ![image](https://private-user-images.githubusercontent.com/99788018/322693315-874e789b-9e05-4007-a8c0-c34d3e7b6e9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk1NTUsIm5iZiI6MTcxMzIzOTI1NSwicGF0aCI6Ii85OTc4ODAxOC8zMjI2OTMzMTUtODc0ZTc4OWItOWUwNS00MDA3LWE4YzAtYzM0ZDNlN2I2ZTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YTA1YmJlOGZmZWExMmI4ZjhkYTRlZDcwYzMyMDAzZDUzMTRmZGMzNzNjYThlZjY1NGFjMjk2MGY3NmU2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZmELm6q4HwO0ppgyavaCBVnhw6FiM6PTsWnfk5J6nBA)
>    ![image](https://private-user-images.githubusercontent.com/99788018/322693396-2a4ea206-68ad-47b6-8dca-1761fc11d3fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk1NTUsIm5iZiI6MTcxMzIzOTI1NSwicGF0aCI6Ii85OTc4ODAxOC8zMjI2OTMzOTYtMmE0ZWEyMDYtNjhhZC00N2I2LThkY2EtMTc2MWZjMTFkM2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYmJmYmEzMzg0OWQyNGEzNGE2MWJiMDY5YTBkZDg0MjgxMWI2MTJiYTBlN2U2ZGEyNzI1MDZhNDJlOGY3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K00lQZU7FmoGJYwkVyVYyTiWwxFu8mBCsyQgGFWFffA)
> 
> here is my test wfs,but this operation in ds3.2.1, force success b, can't skip b, next time, it will run fail again.
> 
> [skip_test.json](https://github.com/apache/dolphinscheduler/files/14986517/skip_test.json)

I understand your case, since change the status of a task instance in  running workflow instance might cause incorrect problem, so this is cannot be simple hot fix, this will be fixed by 3.3.0 hope you can understand.

**Comment by Thomas-HuWei** [comment] 2024-04-16 03:53
@ruanwenjun  OK, I also think this is not easy to fix, have you plan how to release the version 3.3.0 ?

**Comment by ruanwenjun** [comment] 2024-04-16 04:00
> @ruanwenjun OK, I also think this is not easy to fix, have you plan how to release the version 3.3.0 ?

Maybe after May.

**Comment by Thomas-HuWei** [comment] 2024-04-16 08:19
@ruanwenjun 
I finally find a simple way to let force success valid in a running workflow instance.
If its old task instance is force success, set current taskInstance dryRun and can skip this step and run other steps.
Attention that this skip code must before `DefaultTaskExecuteRunnable taskExecuteRunnable =defaultTaskExecuteRunnableFactory.createTaskExecuteRunnable(taskInstance);`
![image](https://github.com/apache/dolphinscheduler/assets/99788018/85da3e71-5e26-4ca1-883a-e26b472f1852)

**Closed as completed** 2024-04-16 08:19 UTC
Labels: bug
