### ISSUE TITLE
[Bug] [dolphinscheduler-service] Python Task execute ERROR 

### ISSUE THREAD

**Issue by zhengxiang5965** [apache/dolphinscheduler#13020] opened 2022-11-28 07:12 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/31379313/204213900-39d56b61-f4d2-4a24-8059-768c1385d2c3.png)
When I used kubernates to deploy Dolphinscheduler and tried to run Python Task, an error occurred. 

### What you expected to happen

After troubleshooting, I found that SH command was used to execute the command file. In the Ubuntu system, the default SH command points to Dash, and Dash cannot use the Source command. This is the first error. After switching back to Bash command, the second error occurred, The "PYTHON_HOME" environment variable in the "/opt/dolphinscheduler/conf/dolphinscheduler_env.sh" file in the Command file points to "/opt/soft/Python". The "PYTHON_HOME" in the official document should actually point to "/usr/bin/python3"

### How to reproduce

Use Kubernates to deploy dolphinscheduler, and then execute Python Task

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment] 2022-11-28 14:27
hi @zx472010602 , this case is not caused by wrong bash, just env issue. U should set a correct python home.

**Comment by zhengxiang5965** [comment] 2022-11-29 06:56
> hi @zx472010602 , this case is not caused by wrong bash, just env issue. U should set a correct python home.

The subshell itself does not load the environment variables of the parent SHELL. The project is also set through the source command, but the command itself does not recognize

**Comment by SbloodyS** [comment] 2022-12-01 09:18
This issue has been fixed in #13028. I'll close it.

**Closed as completed by SbloodyS** 2022-12-01 09:18 UTC
Labels: bug
