### ISSUE TITLE
[Bug] [Audit] The audit log feature is not available

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11800] opened 2022-09-06 08:04 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188580440-77f9105b-48a7-427c-bc71-b083c4ee7652.png)

### What you expected to happen

Audit Logging page for all operations

### How to reproduce

Go to the Log Audit page

### Version

[dev](dev: ds3.1.0-prepare)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stalary** [comment] 2022-09-13 02:39
I had the same problem.

**Comment by caishunfeng** [comment] 2022-09-20 03:57
It's not a full feature, just the UI and API, without data.

**Comment by caishunfeng** [comment] 2022-09-20 03:58
It's not a bug, I will close this issue.

**Closed as completed by caishunfeng** 2022-09-20 03:58 UTC
Labels: bug, help wanted, need to verify
