### ISSUE TITLE
[Bug] [dolphinscheduler-ui]ordinary users should not be able to change owned users to admin user

### ISSUE THREAD

**Issue by karen-liu01** [apache/dolphinscheduler#7342] opened 2021-12-12 08:54 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

ordinary users can  change owned users to admin user

### What you expected to happen

ordinary users should not be able to change owned users to admin user

### How to reproduce

1.test_liujinfang login 
2.edit a project,modify owned user to admin 
modified successfully
![image](https://user-images.githubusercontent.com/55787491/145710722-494d6220-bc70-4244-a0cc-9589eb18a783.png)

### Version

2.0.1-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment] 2021-12-13 02:39
I deal with

**Comment by songjianet** [comment] 2021-12-13 13:29
@zhongjiajie @kezhenxu94 This problem can be restricted from the front-end level, but should the back-end interface also increase the corresponding authentication?

**Comment by kezhenxu94** [comment] 2021-12-13 13:49
I'm not sure whether this is by design, a user changing the owner of his projects to others' (admin) is considered to hand over their projects, IMO

**Comment by songjianet** [comment] 2021-12-13 13:56
> I'm not sure whether this is by design, a user changing the owner of his projects to others' (admin) is considered to hand over their projects, IMO

Understood, I will investigate tomorrow.

**Comment by huangwei2013** [comment] 2021-12-14 05:23
It's weird just “edit"  the owner. Usually 
1. "Select the next owner“, when in the same organization
2. "Offer a link/qrcode，etc”， when in the public platform

**Comment by songjianet** [comment] 2021-12-14 10:02
If this problem needs to be changed, you can designate a back-end developer to deal with it first, and then I will deal with it. @zhongjiajie

**Comment by lenboo** [comment] 2021-12-14 15:59
> I'm not sure whether this is by design, a user changing the owner of his projects to others' (admin) is considered to hand over their projects, IMO

+1 , ordinary user can also change his projects to other.

**Comment by zhongjiajie** [comment] 2021-12-15 02:10
> I'm not sure whether this is by design, a user changing the owner of his projects to others' (admin) is considered to hand over their projects, IMO

cc @karen-liu01 I think is expected behavior , so I would close it. You could reopen it if you have further information.

**Closed as completed by zhongjiajie** 2021-12-15 02:10 UTC
Labels: bug, UI

**Comment by karen-liu01** [comment] 2021-12-17 13:33
> I think is expected behavior , so I would close it. You could reopen it if you have further information.

ok，I will check with   product manager
