### ISSUE TITLE
[Bug] The problem when the task flow is set to execute at 0:00 every day

### ISSUE THREAD

**Issue by wq557520** [apache/dolphinscheduler#10378] opened 2022-06-09 04:42 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

任务流设置定时每天0点执行时，补数开始时间如果为1号0点，那会1号的不执行，执行从2号开始补数

### What you expected to happen

1号0点的任务也可以正常补数

### How to reproduce

定时时间设置为每天0点，补数的时候选择1号0点到，5号0点

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment] 2022-06-09 06:04
Hi @wq557520 , I can not reproduce your issue in 2.0.5-release. Are you sure you are using 2.0.5-release?

**Comment by brave-lee** [comment] 2022-09-15 08:30
Since this issue cannot be reproduced and the issue has survived from the previous version, I close it. If you have other information, please open it or propose another one

**Closed as completed by brave-lee** 2022-09-15 08:30 UTC
Labels: bug, backend, need to verify
