### ISSUE TITLE
[Bug] [CommonUtils] not initialize class org.apache.hadoop.conf.Configuration

### ISSUE THREAD

**Issue by 981433814** [apache/dolphinscheduler#6755] opened 2021-11-09 04:12 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I create a new hive node, tip No class found

I'm sure, imported the related package into lib

```shell
class org.apache.hadoop.conf.Configuration
```

我创建了一个hive节点，我已经把相关的包导入到 dolphinscheduler/lib/plugin/task/sql
但是，worker 日志还是报 class org.apache.hadoop.conf.Configuration 的错误

### What you expected to happen

I hope to run the hive node.

### How to reproduce

1. configure hive data source, and the connection is successful.
2. Configure hive node, and run with error.

1. 配置hive数据源，连接成功
2. 配置hive节点，运行报错

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment] 2021-11-10 01:46
The problem is caused by the lack of related jars. I can't confirm which jar it is.
After the data source plug-in features are merged, this problem can be solved.

**Closed as completed** 2021-11-10 02:21 UTC
Labels: bug, Waiting for reply
