### ISSUE TITLE
[Bug] [standalone-server] Caused by: java.lang.NoSuchMethodError: org.apache.dolphinscheduler.service.queue.MasterPriorityQueue.putList(Ljava/util/List;)V

### ISSUE THREAD

**Issue by sdhzwc** [apache/dolphinscheduler#15041] opened 2023-10-18 08:07 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1726" alt="16a4d327a99a57b79cfaa155a9a6678" src="https://github.com/apache/dolphinscheduler/assets/46134044/9d7c770a-2888-4aec-beaf-c4cdeaa16f6b">
3.2.0发版的包 是不是有点问题 我反编译之后putList确实不存在了
<img width="1752" alt="f6a12e3b7c9cc2f0e5a7837a60f4b74" src="https://github.com/apache/dolphinscheduler/assets/46134044/87774f4f-8952-4293-ad10-ed65db816689">
 在2023.9.14之后已经有putList变成putAll了

### What you expected to happen

根据github上3.2.0的源码进行编译 运行是没啥问题的

### How to reproduce

从官网下载二进制包，进入bin,运行bash ./bin/dolphinscheduler-daemon.sh start standalone-server 之后会启动失败

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment] 2023-10-19 01:25
I can successfully reproduce this issue locally with package `https://dlcdn.apache.org/dolphinscheduler/3.2.0/apache-dolphinscheduler-3.2.0-bin.tar.gz`. cc @zhongjiajie

**Comment by zhongjiajie** [comment] 2023-10-19 01:37
@sdhzwc you try to build from which branch and it can run?

**Comment by sdhzwc** [comment] 2023-10-19 01:38
> @sdhzwc 您尝试从哪个分支构建并且可以运行?

3.2.0

**Comment by zhongjiajie** [comment] 2023-10-19 01:39
tag 3.2.0 or branch 3.2.0-release?

**Comment by sdhzwc** [comment] 2023-10-19 01:42
> tag 3.2.0 or branch 3.2.0-release?
![image](https://github.com/apache/dolphinscheduler/assets/46134044/2d31cf60-c50b-44cf-8abd-a4082e7bf6e8)

**Comment by zhongjiajie** [comment] 2023-10-19 01:53
will take a look

**Comment by zhongjiajie** [comment] 2023-10-19 06:30
I have update the dist tarball directly instead of create a new release, because we have no code change. I try the binary tarball in https://dist.apache.org/repos/dist/release/dolphinscheduler/3.2.0/,  and found out it work, but in https://www.apache.org/dyn/closer.lua/dolphinscheduler/3.2.0/apache-dolphinscheduler-3.2.0-bin.tar.gz is do not work. Maybe https://www.apache.org/dyn/closer.lua/ need some time to flush the cache

**Comment by zhongjiajie** [comment] 2023-10-20 06:26
> I have update the dist tarball directly instead of create a new release, because we have no code change. I try the binary tarball in https://dist.apache.org/repos/dist/release/dolphinscheduler/3.2.0/, and found out it work, but in https://www.apache.org/dyn/closer.lua/dolphinscheduler/3.2.0/apache-dolphinscheduler-3.2.0-bin.tar.gz is do not work. Maybe https://www.apache.org/dyn/closer.lua/ need some time to flush the cache

update to Oct 20, 2023, our download link https://dolphinscheduler.apache.org/en-us/download/3.2.0 work now and is the same as https://dist.apache.org/repos/dist/release/dolphinscheduler/3.2.0/

Thanks @sdhzwc for submitting the issue and @SbloodyS for the notification, will close the issue now

**Closed as completed by zhongjiajie** 2023-10-20 06:26 UTC
Labels: bug, priority:high
