### ISSUE TITLE
Can`t edit worker group

### ISSUE THREAD

**Issue by drowecho** [apache/dolphinscheduler#4842] opened 2021-02-23 03:15 UTC
![image](https://user-images.githubusercontent.com/56685203/108798136-fdaf5500-75c7-11eb-90c5-09b0af294bba.png)

it works perfect!
but after start the dolphinscheduler server, i can`t edit or change worker group message

it`s my contains in dolphinscheduler-1.3.5/conf/config/install_config.conf file :
  
  `# postgresql or mysql
  dbtype="mysql"
  
  # db config
  # db address and port
  dbhost="mcpqa8:3306"
  
  # db username
  username="root"
  
  # database name
  dbname="dolphinscheduler"
  
  # db passwprd
  # NOTICE: if there are special characters, please use the \ to escape, for example, `[` escape to `\[`
  password="123456"
  
  # zk cluster
  zkQuorum="mcpqa1:2181,mcpqa2:2181,mcpqa3:2181"
  
  # Note: the target installation path for dolphinscheduler, please not config as the same as the current path (pwd)
  installPath="/home/mwit/dolphinscheduler-1.3.5"
  
  # deployment user
  # Note: the deployment user needs to have sudo privileges and permissions to operate hdfs. If hdfs is enabled, the root directory needs to be created by itself
  deployUser="mwit"
  
  mailProtocol="SMTP"
  
  # alert config
  # mail server host
  mailServerHost="smtp.exmail.qq.com"
  
  # mail server port
  # note: Different protocols and encryption methods correspond to different ports, when SSL/TLS is enabled, make sure the port is correct.
  mailServerPort="465"
  
  # sender
  mailSender=""
  
  # user
  mailUser=""
  
  # sender password
  # note: The mail.passwd is email service authorization code, not the email login password.
  mailPassword=""
  
  # TLS mail protocol support
  starttlsEnable="false"
  
  # SSL mail protocol support
  # only one of TLS and SSL can be in the true state.
  sslEnable="true"
  
  #note: sslTrust is the same as mailServerHost
  sslTrust="smtp.exmail.qq.com"
  
  
  # resource storage type：HDFS,S3,NONE
  resourceStorageType="HDFS"
  
  # if resourceStorageType is HDFS，defaultFS write namenode address，HA you need to put core-site.xml and hdfs-site.xml in the conf directory.
  # if S3，write S3 address，HA，for example ：s3a://dolphinscheduler，
  # Note，s3 be sure to create the root directory /dolphinscheduler
  defaultFS="hdfs://mcpqa1:8020"
  
  # if resourceStorageType is S3, the following three configuration is required, otherwise please ignore
  s3Endpoint="http://192.168.xx.xx:9010"
  s3AccessKey="xxxxxxxxxx"
  s3SecretKey="xxxxxxxxxx"
  
  # if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
  yarnHaIps="mcpqa1,mcpqa2,mcpqa3,mcpqa4,mcpqa5,mcpqa6,mcpqa7,mcpqa8"
  
  # if resourcemanager HA enable or not use resourcemanager, please skip this value setting; If resourcemanager is single, you only need to replace yarnIp1 to actual resourcemanager hostname.
  singleYarnIp="yarnIp1"
  
  # resource store on HDFS/S3 path, resource file will store to this hadoop hdfs path, self configuration, please make sure the directory exists on hdfs and have read write permissions。/dolphinscheduler is recommended
  resourceUploadPath="/user/dolphinscheduler"
  
  # who have permissions to create directory under HDFS/S3 root path
  # Note: if kerberos is enabled, please config hdfsRootUser=
  hdfsRootUser="hdfs"
  
  # kerberos config
  # whether kerberos starts, if kerberos starts, following four items need to config, otherwise please ignore
  kerberosStartUp="false"
  # kdc krb5 config file path
  krb5ConfPath="$installPath/conf/krb5.conf"
  # keytab username
  keytabUserName="hdfs-mycluster@ESZ.COM"
  # username keytab path
  keytabPath="$installPath/conf/hdfs.headless.keytab"
  
  
  # api server port
  apiServerPort="12345"
  
  
  # install hosts
  # Note: install the scheduled hostname list. If it is pseudo-distributed, just write a pseudo-distributed hostname
  ips="mcpqa1,mcpqa2,mcpqa3,mcpqa4,mcpqa5,mcpqa6,mcpqa7,mcpqa8"
  
  # ssh port, default 22
  # Note: if ssh port is not default, modify here
  sshPort="22"
  
  # run master machine
  # Note: list of hosts hostname for deploying master
  masters="mcpqa1,mcpqa2"
  
  # run worker machine
  # note: need to write the worker group name of each worker, the default value is "default"
  workers="mcpqa1:default,mcpqa2:default,mcpqa3:default,mcpqa4:default,mcpqa5:default,mcpqa6:default,mcpqa7:default,mcpqa8:default"
  
  # run alert machine
  # note: list of machine hostnames for deploying alert server
  alertServer="mcpqa2"
  
  # run api machine
  # note: list of machine hostnames for deploying api server
  apiServers="mcpqa1"`

**Comment by xingchun-chen** [comment] 2021-02-25 03:08
the issue is the same as #3730, will close it

**Closed as completed by xingchun-chen** 2021-02-25 03:08 UTC
