### ISSUE TITLE
[Feature][UI Next][V1.0.0-Alpha] Incorrect coloring of dashboards in light mode

### ISSUE THREAD

**Issue by ronyang1985** [apache/dolphinscheduler#8654] opened 2022-03-02 06:11 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in light mode, the dashboard is like this
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/13843983/156304840-d54800a7-1d2f-48ee-8f3b-28665b80d83f.png">

in dark mode, it is like this
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/13843983/156304869-df5c244f-69a5-42f7-9f8f-d3f1e3393961.png">

### What you expected to happen

coloring of dashboards display correctly

### How to reproduce

launch ui-next and visit monitor module

The color is incorrect both worker and master dashboard

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment] 2022-03-02 06:36
Thank you for your feedback. I think this is not a bug, it is a point that can be optimized, you can refer to the content of this issue https://github.com/apache/dolphinscheduler/issues/8565 , for the current issue, I will close it.

**Closed as completed** 2022-03-02 06:37 UTC
Labels: feature, UI
