### ISSUE TITLE
[Bug-FE][UI Next][V1.0.0-Alpha]Project workflow import error report

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#9329] opened 2022-04-02 07:56 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Project workflow import error report

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/76080484/161372830-0c3c07b4-eb2a-4612-9ad0-b0472e87f6ec.png">

### What you expected to happen

Project workflow import is normal

### How to reproduce

Project workflow import error report

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Amy0104** [comment] 2022-04-02 08:20
This seems to be no problem.

**Comment by songjianet** [comment] 2022-04-08 11:19
We can't reproduce this issue, so I'll close it.

**Closed as completed** 2022-04-08 11:20 UTC
Labels: bug, UI, priority:middle
