### ISSUE TITLE
[Bug] [UI] press Enter key get "true" not new line

### ISSUE THREAD

**Issue by Jiezhi** [apache/dolphinscheduler#7514] opened 2021-12-21 03:26 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In shell task `Script` editbox, when you input some special char(!@#$%...) and you press 'Enter' key to next line.

While you just get `true` str afterwards.

![image](https://user-images.githubusercontent.com/3399929/146865778-45eaabae-4bf5-44e2-82bd-68f8bb3a5572.png)

### What you expected to happen

Clearly, cursor to new line not `true`.

### How to reproduce

See `What happened`

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment] 2021-12-22 03:07
I'll fix it.

**Comment by zhongjiajie** [comment] 2021-12-22 03:08
> I'll fix it.

@devosend  I assigned to you, looking forward your contribution.

**Comment by devosend** [comment] 2021-12-23 14:07
press Enter key get "true" is not a bug. this is beause `Enter` key is shortcut for autocomplete. I submit a pr to ignore this shortcut. But you can still complete by `Tab` shortcut now.

**Comment by zhongjiajie** [comment] 2022-01-23 12:37
no stale

**Closed as completed** 2022-01-28 10:25 UTC
Labels: bug
