### ISSUE TITLE
Could not find or load main class org.apache.zookeeper.ZooKeeperMain

### ISSUE THREAD

**Issue by 391518331** [apache/dolphinscheduler#10029] opened 2022-05-13 10:56 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

3.0.0   sh ./bin/install.sh  

3.stop server
17.0.237.209:default
17.0.133.220:default
17.0.133.220:default
17.0.206.7 master server is stopping
Begin stop master-server......
no master-server to stop
End stop master-server.
17.0.137.109 master server is stopping
Begin stop master-server......
no master-server to stop
End stop master-server.
17.0.237.209 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
17.0.133.220 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
Begin stop alert-server......
no alert-server to stop
End stop alert-server.
17.0.237.209 api server is stopping
Begin stop api-server......
no api-server to stop
End stop api-server.
4.delete zk node
Error: Could not find or load main class org.apache.zookeeper.ZooKeeperMain

### What you expected to happen

Cluster installation

### How to reproduce

Cluster installation

### Anything else

no

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 391518331** [comment] 2022-05-13 11:22
zookepeer3.8.0

**Comment by songjianet** [comment] 2022-05-14 00:42
Thank you for your feedback.

**Comment by SbloodyS** [comment] 2022-05-14 03:50
This issue has been fixed in ```dev``` branch. You can try it or wait ```3.0.0-beta-1``` release.

**Comment by xizhou-Rain** [comment] 2022-05-18 07:59
I also encounter the same problem. Besides waiting for repair, is there any solution?

**Comment by GodWon** [comment] 2022-06-10 01:01
> This issue has been fixed in `dev` branch. You can try it or wait `3.0.0-beta-1` release.

3.0.0-beta-1 还是存在同样的问题

**Comment by rayxo** [comment] 2022-06-16 06:11
> This issue has been fixed in `dev` branch. You can try it or wait `3.0.0-beta-1` release.
@SbloodyS  meet same error in 3.0.0-beta-1

**Comment by SbloodyS** [comment] 2022-06-16 07:21
Could you describe the steps to reproduce this problem? @rayxo @GodWon

**Comment by rayxo** [comment] 2022-06-16 07:57
> Could you describe the steps to reproduce this problem? @rayxo @GodWon

![image](https://user-images.githubusercontent.com/8943370/174021464-e185236e-0681-495c-8d0d-2f2ac7d0941c.png)

**Comment by dawn2004cn** [comment] 2022-06-17 10:05
hd.n1 master server is stopping
Begin stop master-server......
no master-server to stop
End stop master-server.
hd.n2 master server is stopping
Begin stop master-server......
no master-server to stop
End stop master-server.
hd.m1 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
hd.m2 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
hd.n1 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
hd.n2 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
hd.n3 worker server is stopping
Begin stop worker-server......
no worker-server to stop
End stop worker-server.
Begin stop alert-server......
no alert-server to stop
End stop alert-server.
hd.m2 api server is stopping
Begin stop api-server......
no api-server to stop
End stop api-server.
4.delete zk node
Error: Could not find or load main class org.apache.zookeeper.ZooKeeperMain

我也出现这个问题，3.0.0-beta-1 版本

**Comment by SbloodyS** [comment] 2022-06-17 10:07
@EricGao888 @liqingwang Do you guys have time to take a look at this issue?

**Comment by EricGao888** [comment] 2022-06-17 10:13
> @EricGao888 @liqingwang Do you guys have time to take a look at this issue?

I will take a look this weekend.

**Comment by EricGao888** [comment] 2022-06-18 09:43
Will check this issue later today. BTW, one interesting thing in `Release Notes - ZooKeeper - Version 3.8.0` is that `ZooKeeperMain` was refactored. 

![image](https://user-images.githubusercontent.com/34905992/174432161-3df96623-f732-44b7-95e8-c19e5e65dc65.png)

https://issues.apache.org/jira/browse/ZOOKEEPER-3581

https://github.com/apache/zookeeper/pull/1255/files#diff-ac2f8dda96fddcdaf049aefa76a1ce10fc6cbc37327c860742c5e362caa998aa

**Comment by SbloodyS** [comment] 2022-06-18 11:53
https://github.com/apache/dolphinscheduler/blob/4be3b877c3c143e2b5c58c017b641fd927c0dff5/.github/workflows/cluster-test/mysql/docker-compose-base.yaml#L36-L44

The 3.8.0 version of zookeeper is used in our Ci. And it can run normally. In the cluster test of CI. ```install.sh``` is not used for installation, but the configuration file is modified after decompression. It seems the problem is in the `install.sh` script. @EricGao888

**Comment by Desperado2** [comment] 2022-06-20 12:48
一下处理方式，请测有效
1）新增registryServers=$REGISTRY_ZOOKEEPER_CONNECT_STRING
2）修改export DOLPHINSCHEDULER_LIB_JARS=$DOLPHINSCHEDULER_HOME/libs/*为export DOLPHINSCHEDULER_LIB_JARS=$DOLPHINSCHEDULER_HOME/api-server/libs/*

**Comment by SbloodyS** [comment] 2022-06-20 13:27
> 一下处理方式，请测有效 1）新增registryServers=$REGISTRY_ZOOKEEPER_CONNECT_STRING 2）修改export DOLPHINSCHEDULER_LIB_JARS=$DOLPHINSCHEDULER_HOME/libs/_为export DOLPHINSCHEDULER_LIB_JARS=$DOLPHINSCHEDULER_HOME/api-server/libs/_

Well done. Would you like to submit a PR to fix this?

BTW, please use English in order to make everyone understand.

**Comment by Desperado2** [comment] 2022-06-21 07:49
> > 一下处理方式，请测有效 1）新增registryServers=$REGISTRY_ZOOKEEPER_CONNECT_STRING 2）修改export DOLPHINSCHEDULER_LIB_JARS=$DOLPHINSCHEDULER_HOME/libs/_为export DOLPHINSCHEDULER_LIB_JARS=$DOLPHINSCHEDULER_HOME/api-server/libs/_
> 
> Well done. Would you like to submit a PR to fix this?
> 
> BTW, please use English in order to make everyone understand.

A PR has been submitted to fix this
thans

**Closed as completed** 2022-06-21 09:26 UTC
Labels: bug, backend
