### ISSUE TITLE
Custom task task node mvn clean package error

### ISSUE THREAD

**Issue by qinheqin** [apache/dolphinscheduler#16415] opened 2024-08-02 10:10 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[ERROR] Some problems were encountered while processing the POMs：
![image](https://github.com/user-attachments/assets/fed41c43-3202-4356-9b33-2c4b9f7633fc)
关于 dolphinscheduler-bom:pom:3.2.2    没有找到
![image](https://github.com/user-attachments/assets/c269141e-927c-4ff3-9086-e7bca49ca688)
pom.xml
![image](https://github.com/user-attachments/assets/875aea43-ae8e-4a46-9a33-3a22c8cd21eb)

### What you expected to happen

不清楚  可能 环境配置问题

### How to reproduce

 mvn clean package  task . 
![image](https://github.com/user-attachments/assets/34e043a1-46f9-47f5-a25a-e4718c4eaa86)

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment] 2024-08-02 12:45
This is not a bug. Closing for now.

**Closed as completed by SbloodyS** 2024-08-02 12:45 UTC
Labels: wontfix
