### ISSUE TITLE
[Bug] [MySQL Connection] Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

### ISSUE THREAD

**Issue by CryptoColin** [apache/dolphinscheduler#8783] opened 2022-03-09 14:00 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm trying to connect to tidb and reporting this error:
<img width="1179" alt="Screen Shot 2022-03-09 at 9 39 08 PM" src="https://user-images.githubusercontent.com/89381700/157453743-dad2a90e-0d3c-4120-a9e9-2cc7ae425f7d.png">

### What you expected to happen

connect successfully

### How to reproduce

version 2.0.3 k8s model

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment] 2022-03-10 00:38
Due to the license incompatibility, we don't have the `mysql-connector-java`, if you need to use this driver, you need to add this dependency and build the image by yourself. You can get more information about how to build an image at [How to build a Docker image](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/installation/docker.html)

Since this not a bug, I just close this issue, if you have more problem about this you can still reply at this issue.

**Closed as completed by ruanwenjun** 2022-03-10 00:38 UTC
Labels: bug, wontfix, kubernetes, release cherry-pick

**Comment by CryptoColin** [comment] 2022-03-10 02:26
thanks,it works

**Comment by fyzn12** [comment] 2023-06-13 07:40
> I also encountered the same bug, please tell me how to solve it

**Comment by fyzn12** [comment] 2023-06-13 07:42
> The version is 3.1.6-SNAPSHOT, which is a cluster created in the k8s environment
