### ISSUE TITLE
[BUG] many dependent tasks depend on a node, task status bug

### ISSUE THREAD

**Issue by wen-hemin** [apache/dolphinscheduler#2112] opened 2020-03-08 05:20 UTC
**Describe the bug**
When many dependent tasks depend on a node and the dependent task supports failed retry, the task that submitted the retry will be judged as kill. causes process instance to fail.

I think, no need to verify process strategy when submitting tasks.

The method updateProcessInstanceState of the MasterExecThread class has been verify process strategy.

```
    private void updateProcessInstanceState() {
        ExecutionStatus state = getProcessInstanceState();
        if(processInstance.getState() != state){
```

```
    private ExecutionStatus getProcessInstanceState(){
        ProcessInstance instance = processService.findProcessInstanceById(processInstance.getId());
        ExecutionStatus state = instance.getState();

        if(activeTaskNode.size() > 0){
            return runningState(state);
        }
        // process failure
        if(processFailed()){
            return ExecutionStatus.FAILURE;
        }
```

```
    private Boolean processFailed(){
        if(hasFailedTask()) {
            if(processInstance.getFailureStrategy() == FailureStrategy.END){
                return true;
            }
            if (processInstance.getFailureStrategy() == FailureStrategy.CONTINUE) {
                return readyToSubmitTaskList.size() == 0 || activeTaskNode.size() == 0;
            }
        }
        return false;
    }
```

**Which version of Dolphin Scheduler:**
 -[1.2.0-preview]

**Comment by lenboo** [comment] 2020-03-09 05:54
![image](https://user-images.githubusercontent.com/29528966/76186000-e555f700-620b-11ea-9bd5-bcc6e1ca8a77.png)

i think the situation is above DAG, 
 1.  failure strategy is "end"
 2.  "2" failed 
 3.  "3" failed and retry, but retry state is "kill"

Is that so？

**Comment by Rubik-W** [comment] 2020-03-09 06:10
yes

**Comment by Rubik-W** [comment] 2020-03-09 06:10
> ![image](https://user-images.githubusercontent.com/29528966/76186000-e555f700-620b-11ea-9bd5-bcc6e1ca8a77.png)
> 
> i think the situation is above DAG,
> 
> 1. failure strategy is "end"
> 2. "2" failed
> 3. "3" failed and retry, but retry state is "kill"
> 
> Is that so？
> 
> @Rubik-W

yes

**Comment by lenboo** [comment] 2020-03-09 07:44
the key is the design of  failure strategy, 
whether we can submit tasks (retry tasks /new tasks) to run when strategy is "end".
when strategy is "end", i think we should not submit any tasks(retry /new ) to run if there have task failed, so it's right to commit to "kill" status

关键是失效策略的设计，当策略为“结束”时是否可以继续提交任务（重试/新任务）以运行。
当策略为“结束”时，我认为如果任务失败，不应该提交任何要运行的任务（重试/新任务）,所以提交kill状态是正确的。

**Comment by Rubik-W** [comment] 2020-03-09 08:15
Before submitting the failure task, it has been verified whether it is a retry task.
So, in the process of submitting the task, there is no need to check the failure status again.

In the design business, the retry task is processed first, then the failed policy is processed.

MasterExecThread.java
task.taskCanRetry()
```
                // node fails, retry first, and then execute the failure process
                if(task.getState().typeIsFailure()){
                    if(task.getState() == ExecutionStatus.NEED_FAULT_TOLERANCE){
                        this.recoverToleranceFaultTaskList.add(task);
                    }
                    if(task.taskCanRetry()){
                        addTaskToStandByList(task);
                    }else{
                        completeTaskList.put(task.getName(), task);
                        if( task.getTaskType().equals(TaskType.CONDITIONS.toString()) ||
                                haveConditionsAfterNode(task.getName())) {
                            submitPostNode(task.getName());
```

**Comment by lenboo** [comment] 2020-03-09 08:38
> Before submitting the failure task, it has been verified whether it is a retry task.
> So, in the process of submitting the task, there is no need to check the failure status again.
> 
> In business design, the retry task is processed first, then the failure strategy is processed.
> 
> MasterExecThread.java
> task.taskCanRetry()
> 
> ```
>                 // node fails, retry first, and then execute the failure process
>                 if(task.getState().typeIsFailure()){
>                     if(task.getState() == ExecutionStatus.NEED_FAULT_TOLERANCE){
>                         this.recoverToleranceFaultTaskList.add(task);
>                     }
>                     if(task.taskCanRetry()){
>                         addTaskToStandByList(task);
>                     }else{
>                         completeTaskList.put(task.getName(), task);
>                         if( task.getTaskType().equals(TaskType.CONDITIONS.toString()) ||
>                                 haveConditionsAfterNode(task.getName())) {
>                             submitPostNode(task.getName());
> ```

yes, you are right. there is a check when add retry tasks to standby list , 
but before submitting to run, we should check the failure strategy again when there have some other tasks failed. because other tasks would be failed between standby and submitted.

**Comment by Rubik-W** [comment] 2020-03-09 10:04
Yes, The processing of current task results and the submission of tasks are serial. I think this is a low probability event, instant optimization into parallel processing, it cannot absolutely solve the problem. Because at any moment when a task is submitting, there may be new failed tasks.

I found another problem:
When obtaining the active task execution result, if first task is success, second task is failure, failure strategy is end model. In the current code logic, subsequent nodes of successful tasks are added to the list to be submitted. 
In business, no tasks should be added. And the end of the workflow should not go to sleep.

Method updateProcessInstanceState() should be executed before method submitStandByTask().

```
            if(canSubmitTaskToQueue()){
                submitStandByTask();
            }
            try {
                Thread.sleep(Constants.SLEEP_TIME_MILLIS);
            } catch (InterruptedException e) {
                logger.error(e.getMessage(),e);
            }
            updateProcessInstanceState();
```

**Comment by lenboo** [comment] 2020-03-09 11:00
1. the submission of tasks may be happened a long time after standby when memory/cpu load 
are not enough, we cannot know what would happened during this period.

2. In business, new tasks should not be standby list when trigger failed policies "end". 
but in order to prompt user why the workflow cannot continue, i think it's appropriate to submit a "kill" task.

3.  the order of submission task  and updating state is not very important.

4. yes, sleep can be move to the beginning of the loop.

**Comment by Rubik-W** [comment] 2020-03-09 11:39
1:
a) If the master server  is under-loaded, will only affect the submission of tasks. The Master will continue to process task results, when the failed task is found, it is directly processed.
b) If the worker server  is under-loaded, the task will not be executed, the master finds a failed task, and the worker task will be killed.

2:
This happens because of failed tasks, the user is able to know the cause of the failure.

If many tasks depend on one task, there will be many kill tasks, which will easily mislead the user,
 we have already seen this happen.

3:
There is a failed task and a failure strategy is triggered. It no longer makes sense to continue to submit tasks.

4: I agree

**Comment by Rubik-W** [comment] 2020-03-12 03:11
Oh, I see

> Method updateProcessInstanceState() should be executed before method submitStandByTask().

This modification is wrong, the purpose of submitting a task is to record the status of the workflow execution. Designed for workflow failure retry.
So, the core problem is that a failed retry task cannot be determined as a workflow failure.

**Comment by Rubik-W** [comment] 2020-03-12 03:50
New modification plan:
1.The method runProcess() of the MasterExecThread class. Update instance status before submitting task.

```
            updateProcessInstanceState();

            if (canSubmitTaskToQueue()) {
                submitStandByTask();
            }

            if (processInstance.IsProcessInstanceStop()) {
                break;
            }

            try {
                Thread.sleep(Constants.SLEEP_TIME_MILLIS);
            } catch (InterruptedException e) {
                logger.error(e.getMessage(),e);
            }
```

2.The method getSubmitTaskState() of the ProcessDao class. If instance status is failure, the task status is set to kill.

```
        if( processInstanceState == ExecutionStatus.READY_PAUSE){
            state = ExecutionStatus.PAUSE;
        }else if(processInstanceState == ExecutionStatus.READY_STOP
                || processInstanceState == ExecutionStatus.FAILURE) {
            state = ExecutionStatus.KILL;
        }else{
            state = ExecutionStatus.SUBMITTED_SUCCESS;
        }
```

**Comment by Rubik-W** [comment] 2020-03-12 04:06
> ![image](https://user-images.githubusercontent.com/29528966/76186000-e555f700-620b-11ea-9bd5-bcc6e1ca8a77.png)
> 
> i think the situation is above DAG,
> 
> 1. failure strategy is "end"
> 2. "2" failed
> 3. "3" failed and retry, but retry state is "kill"
> 
> Is that so？
> 
> @Rubik-W

1. failure strategy is "end"
2. failed and retry
3. failed and retry, but retry state is "kill"

**Comment by Rubik-W** [comment] 2020-03-13 07:46
@lenboo  Please read the last three replies again.

**Comment by lenboo** [comment] 2020-03-17 08:48
> New modification plan:
> 1.The method runProcess() of the MasterExecThread class. Update instance status before submitting task.
> 
> ```
>             updateProcessInstanceState();
> 
>             if (canSubmitTaskToQueue()) {
>                 submitStandByTask();
>             }
> 
>             if (processInstance.IsProcessInstanceStop()) {
>                 break;
>             }
> 
>             try {
>                 Thread.sleep(Constants.SLEEP_TIME_MILLIS);
>             } catch (InterruptedException e) {
>                 logger.error(e.getMessage(),e);
>             }
> ```
> 
> 2.The method getSubmitTaskState() of the ProcessDao class. If instance status is failure, the task status is set to kill.
> 
> ```
>         if( processInstanceState == ExecutionStatus.READY_PAUSE){
>             state = ExecutionStatus.PAUSE;
>         }else if(processInstanceState == ExecutionStatus.READY_STOP
>                 || processInstanceState == ExecutionStatus.FAILURE) {
>             state = ExecutionStatus.KILL;
>         }else{
>             state = ExecutionStatus.SUBMITTED_SUCCESS;
>         }
> ```
> 
> @lenboo

the order of submission task and updating state is not very important.
in dolphinscheduler, master and worker run asynchronously,   the "strategy end" can be  triggered at any time, maybe between updating process state and submitting the next tasks. so the strategy checking  is  necessary when submitting task.

**Comment by Rubik-W** [comment] 2020-03-21 03:31
@lenboo 
The problem is the trigger point for the "strategy end". I think the responsibilities should be clear.
When submitting tasks, the task processing thread should only care about the state of the process instance.
MasterExecThread controls the main process, and to check the "strategy end".
Unified caliber, instead of checking "strategy end" everywhere.

This is also the purpose of updating the process status before submitting the task.

**Comment by Rubik-W** [comment] 2020-05-05 00:35
It's time to solve this problem.

**Comment by lenboo** [comment] 2022-01-05 03:40
Already fixed in 2.x

**Closed by lenboo** 2022-01-05 03:40 UTC
Labels: bug, need to verify
