### ISSUE TITLE
[Bug] [dolphinscheduler-ui]The back-end interface is invoked twice with the same conditional search

### ISSUE THREAD

**Issue by karen-liu01** [apache/dolphinscheduler#7344] opened 2021-12-12 10:20 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

search with the same project name,the back-end interface is invoked twice 

### What you expected to happen

1.should be called  once  or Search every time you click
2.Hitting Enter should also work

### How to reproduce

1.admin login
2.Go to this URL  http://ip:12345/dolphinscheduler/ui/#/projects/list  
3.input 2021 ,click search button
4.click search button again 
5.click search button again  click search button again 
the back-end interface is invoked only twice   

### Version

2.0.1-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment] 2021-12-13 02:40
I deal with

**Comment by songjianet** [comment] 2021-12-13 13:35
@karen-liu01 The problem is that after clicking the search twice, clicking the search again does not call the interface, does it?

**Comment by songjianet** [comment] 2021-12-14 07:33
@karen-liu01 @zhongjiajie I checked the code in the project and found that this is an optimized strategy. For the same search content, no interface call is made. You can try to change the search content. I don’t know if there is still need to make changes to this question.

**Comment by zhongjiajie** [comment] 2021-12-14 09:36
> @karen-liu01 @zhongjiajie I checked the code in the project and found that this is an optimized strategy. For the same search content, no interface call is made. You can try to change the search content. I don’t know if there is still need to make changes to this question.

@songjianet  sorry I do know either, maybe ping @lenboo @CalvinKirs

**Comment by songjianet** [comment] 2021-12-14 10:00
> > @karen-liu01 @zhongjiajie I checked the code in the project and found that this is an optimized strategy. For the same search content, no interface call is made. You can try to change the search content. I don’t know if there is still need to make changes to this question.
> 
> @songjianet sorry I do know either, maybe ping @lenboo @CalvinKirs

He will reply to this question and close it.@lenboo

**Comment by lenboo** [comment] 2021-12-14 15:50
> @karen-liu01 @zhongjiajie I checked the code in the project and found that this is an optimized strategy. For the same search content, no interface call is made. You can try to change the search content. I don’t know if there is still need to make changes to this question.

yes, maybe this is a very effective strategy in limiting duplicate data . 
If you have other ideas, we can discuss them again.

**Comment by zhongjiajie** [comment] 2021-12-15 02:04
Will close this issue. @karen-liu01 @songjianet you could reopen it if have further info.

**Closed as completed by zhongjiajie** 2021-12-15 02:04 UTC
Labels: bug, UI

**Comment by karen-liu01** [comment] 2021-12-18 06:32
> yes, maybe this is a very effective strategy in limiting duplicate data .
> If you have other ideas, we can discuss them again.

ok，I got  the optimized strategy.
