### ISSUE TITLE
[Bug] Failed to create tenant

### ISSUE THREAD

**Issue by QuakeWang** [apache/dolphinscheduler#9982] opened 2022-05-11 05:11 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When creating a tenant, if the name starts with a capital letter, an error will be reported. Lowercase letters are fine.

### What you expected to happen

Tenants can be created normally.

### How to reproduce

![tenant](https://user-images.githubusercontent.com/45645138/167773380-ba04eb8c-74df-43fd-a22f-16e8f7c257cd.gif)

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by paul8263** [comment] 2022-05-12 06:53
Hi @QuakeWang ,
I cannot reproduce this issue with latest dev branch.
Could you please verify the create tenant POST request payload by paying attention to tenantCode field? The backend seems not to be the root cause.

**Comment by QuakeWang** [comment] 2022-05-12 07:36
> Hi @QuakeWang , I cannot reproduce this issue with latest dev branch. Could you please verify the create tenant POST request payload by paying attention to tenantCode field? The backend seems not to be the root cause.

I have re-test it. The version is 3.0.0-beta, and it worked finely.

**Comment by caishunfeng** [comment] 2022-05-18 06:44
> > Hi @QuakeWang , I cannot reproduce this issue with latest dev branch. Could you please verify the create tenant POST request payload by paying attention to tenantCode field? The backend seems not to be the root cause.
> 
> I have re-test it. The version is 3.0.0-beta, and it worked finely.

Thanks, I will close this issue.

**Closed as completed by caishunfeng** 2022-05-18 06:44 UTC
Labels: bug, backend
