### ISSUE TITLE
[Bug] [Module Name] Server-side exception: task instance is null or host is null

### ISSUE THREAD

**Issue by touchhuang** [apache/dolphinscheduler#14923] opened 2023-09-14 08:22 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task displays submission success by master, but not excute by worker. how to fix it?

![image](https://github.com/apache/dolphinscheduler/assets/25630441/e73bc725-0d5b-4fb5-b64d-24bb59334a49)

![image](https://github.com/apache/dolphinscheduler/assets/25630441/7d735c29-6f41-4332-81c7-95bbc56b7709)

### What you expected to happen

task need done well

### How to reproduce

![img_v2_b47fd2b6-efa2-44b9-9889-5f733736de0g](https://github.com/apache/dolphinscheduler/assets/25630441/3ede75bd-d66f-466c-a139-596cf4028fca)

### Anything else

sometimes

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AmriStrong** [comment] 2023-09-14 09:02
Please check if worker Group management is configured correctly?
security  -> worker group manage 
![image](https://github.com/apache/dolphinscheduler/assets/24251573/43b76458-e177-4819-90a3-c7a70e8061a3)

**Comment by touchhuang** [comment] 2023-09-14 13:02
There are no errors in the configuration. but it work well after stop some error instance, I found a large number of errors msg with another workGroup in master-log when this error occurred.  Does this have an impact?
![image](https://github.com/apache/dolphinscheduler/assets/25630441/ff302eae-cc1a-4e30-8e35-c010f1f58bc5)
![image](https://github.com/apache/dolphinscheduler/assets/25630441/d49d7bd1-3a8e-4eb6-b9df-62b39ea43f91)

**Comment by kezhenyang163** [comment] 2023-09-18 12:35
I also encountered a similar problem. When I manually executed the task, this error occurred. After restarting the cluster, it returned to normal. My configuration is a single machine work node.

It seems that the task has not been assigned to the corresponding execution node for execution, and the task has been in the pending state.

**Comment by yihao-tcf** [comment] 2023-10-07 05:25
I have also experienced such problems, which seriously affect the normal operation of scheduled tasks.

version：3.1.7
**Reproduction steps**

**Comment by yihao-tcf** [comment] 2023-10-07 06:07
I have also experienced such problems, which seriously affect the normal operation of scheduled tasks.
**version**：3.1.7

**Reproduction steps**

1. Create Work groups
![2f5457678c7943eaecbdba3976b51cb2](https://github.com/apache/dolphinscheduler/assets/65161474/888f1d3a-5843-4bd5-981c-db111f0854a4)

2. Create Test Tasks(Three different working groups)
   Task 1 use '大数据集群' worker group
      
![71125c534dbed5a09d2402022c8fd444](https://github.com/apache/dolphinscheduler/assets/65161474/39e4f000-1a90-44a5-9f7e-bd415574305f)

   Task 2 use '算法集群' worker group
   
![2a6a238c512ac1c8ef2b539d3732e01f](https://github.com/apache/dolphinscheduler/assets/65161474/6f38fef6-1922-43b7-bed5-4bfa8ad42b59)

   Task 3 use 'default' worker group
   
![a44759155e6f9e76d488f780b940b25a](https://github.com/apache/dolphinscheduler/assets/65161474/d0d1fc4f-0f7f-47d2-8dad-1785a3b1af33)

   Set scheduled execution，online workflow and scheduling
   `* * * * * ? *`
3. Stop the worker of the '算法集群'
![23383d0055ee3d585f29501206eae990](https://github.com/apache/dolphinscheduler/assets/65161474/b35bcda6-51c3-4a2f-bb0f-bf355e58628a)


**After stopping, all tasks will be affected and an error will be reported as task instance is null or host is null.**

After stopping woker group info:
![9b4d332c44a6e62b7ca0854e98456d12](https://github.com/apache/dolphinscheduler/assets/65161474/aefc0176-213e-416d-b7e4-00ac23b161f9)

After stopping task execution status:
![b6582c94c541f103d7d43f14b9ec55ab](https://github.com/apache/dolphinscheduler/assets/65161474/90e4114c-7589-48a0-9912-e0ee278e4acb)
![5e80093fa06d528d3b5303f2b0e5fa69](https://github.com/apache/dolphinscheduler/assets/65161474/dac2288b-aaac-4e55-b9a0-489031da3cad)
![91f4f3c91f706e2cc5f750a1b482c496](https://github.com/apache/dolphinscheduler/assets/65161474/15f3e7f5-3d35-49cc-a65b-871050a85382)
![576601d98be9c6127e3bd64a1820a0b7](https://github.com/apache/dolphinscheduler/assets/65161474/14466014-bfab-46fb-9a6b-c1f9258cdc59)

error logs message：
![98e57f541dc77e1eabe63996bc65c22a](https://github.com/apache/dolphinscheduler/assets/65161474/78b647cc-08b0-4e63-805a-980fe828460e)

After starting the stopped worker, the task resumes execution. A large number of backlogged tasks are resuming execution, which may cause the cluster to be in a high load state and lead to the downtime of other services in the cluster. This is very dangerous

I don't quite understand why the node downtime of the '算法集群' worker group affects the tasks of other worker group nodes

**Comment by yihao-tcf** [comment] 2023-10-07 06:12
> I have also experienced such problems, which seriously affect the normal operation of scheduled tasks. **version**：3.1.7
> 
> **Reproduction steps**
> 
> 1. Create Work groups
>    ![2f5457678c7943eaecbdba3976b51cb2](https://user-images.githubusercontent.com/65161474/273366969-888f1d3a-5843-4bd5-981c-db111f0854a4.png)
> 2. Create Test Tasks(Three different working groups)
>    Task 1 use '大数据集群' worker group
> 
> ![71125c534dbed5a09d2402022c8fd444](https://user-images.githubusercontent.com/65161474/273366981-39e4f000-1a90-44a5-9f7e-bd415574305f.png)
> 
> Task 2 use '算法集群' worker group
> 
> ![2a6a238c512ac1c8ef2b539d3732e01f](https://user-images.githubusercontent.com/65161474/273366987-6f38fef6-1922-43b7-bed5-4bfa8ad42b59.png)
> 
> Task 3 use 'default' worker group
> 
> ![a44759155e6f9e76d488f780b940b25a](https://user-images.githubusercontent.com/65161474/273366991-d0d1fc4f-0f7f-47d2-8dad-1785a3b1af33.png)
> 
> Set scheduled execution，online workflow and scheduling 3. Stop the worker of the '算法集群'`* * * * * ? *` ![23383d0055ee3d585f29501206eae990](https://user-images.githubusercontent.com/65161474/273367007-b35bcda6-51c3-4a2f-bb0f-bf355e58628a.png)
> 
> **After stopping, all tasks will be affected and an error will be reported as task instance is null or host is null.**
> 
> After stopping woker group info: ![9b4d332c44a6e62b7ca0854e98456d12](https://user-images.githubusercontent.com/65161474/273366917-aefc0176-213e-416d-b7e4-00ac23b161f9.png)
> 
> After stopping task execution status: ![b6582c94c541f103d7d43f14b9ec55ab](https://user-images.githubusercontent.com/65161474/273366920-90e4114c-7589-48a0-9912-e0ee278e4acb.png) ![5e80093fa06d528d3b5303f2b0e5fa69](https://user-images.githubusercontent.com/65161474/273366923-dac2288b-aaac-4e55-b9a0-489031da3cad.png) ![91f4f3c91f706e2cc5f750a1b482c496](https://user-images.githubusercontent.com/65161474/273366929-15f3e7f5-3d35-49cc-a65b-871050a85382.png) ![576601d98be9c6127e3bd64a1820a0b7](https://user-images.githubusercontent.com/65161474/273366931-14466014-bfab-46fb-9a6b-c1f9258cdc59.png) ![98e57f541dc77e1eabe63996bc65c22a](https://user-images.githubusercontent.com/65161474/273366935-9ce95af5-b713-4474-a82a-109f700b7540.png)
> 
> error logs message： ![98e57f541dc77e1eabe63996bc65c22a](https://user-images.githubusercontent.com/65161474/273366951-78b647cc-08b0-4e63-805a-980fe828460e.png)
> 
> After starting the stopped worker, the task resumes execution. A large number of backlogged tasks are resuming execution, which may cause the cluster to be in a high load state and lead to the downtime of other services in the cluster. This is very dangerous

I don't quite understand why the node downtime of the '算法集群' worker group affects the tasks of other worker group nodes

**Comment by kezhenyang163** [comment] 2023-10-19 10:49
Log in to the DS machine and run [status-all.sh] to check the health status of DS cluster nodes，When I have this error, it is usually accompanied by a node exception in the cluster，You can prioritize whether it is a machine node problem

![a76f5c716f62a8fb9b8ed7d56429583e](https://github.com/apache/dolphinscheduler/assets/134901781/83bea81d-87cb-4d27-bcd9-2652da78dec8)

After I restarted the cluster, the machine node status returned to normal and the task could be executed normally. However, the cause of DS node death still needs to be further identified according to the specific situation

My problem was that the master and work nodes died abnormally due to insufficient machine resources
So it's not a Bug

**Comment by kezhenyang163** [comment] 2023-10-26 12:07
@touchhuang This error is caused by the abnormal work node, so I think this issue can be closed

**Comment by yihao-tcf** [comment] 2023-10-27 01:04
> @touchhuang This error is caused by the abnormal work node, so I think this issue can be closed

I don't think this is a bug, if one of the worker nodes goes down for some reason, causing all tasks to fail to run. Is this a bug?

**Comment by yihao-tcf** [comment] 2023-10-27 01:09
> I have also experienced such problems, which seriously affect the normal operation of scheduled tasks. **version**：3.1.7
> 
> **Reproduction steps**
> 
> 1. Create Work groups
>    ![2f5457678c7943eaecbdba3976b51cb2](https://user-images.githubusercontent.com/65161474/273366969-888f1d3a-5843-4bd5-981c-db111f0854a4.png)
> 2. Create Test Tasks(Three different working groups)
>    Task 1 use '大数据集群' worker group
> 
> ![71125c534dbed5a09d2402022c8fd444](https://user-images.githubusercontent.com/65161474/273366981-39e4f000-1a90-44a5-9f7e-bd415574305f.png)
> 
> Task 2 use '算法集群' worker group
> 
> ![2a6a238c512ac1c8ef2b539d3732e01f](https://user-images.githubusercontent.com/65161474/273366987-6f38fef6-1922-43b7-bed5-4bfa8ad42b59.png)
> 
> Task 3 use 'default' worker group
> 
> ![a44759155e6f9e76d488f780b940b25a](https://user-images.githubusercontent.com/65161474/273366991-d0d1fc4f-0f7f-47d2-8dad-1785a3b1af33.png)
> 
> Set scheduled execution，online workflow and scheduling 3. Stop the worker of the '算法集群'`* * * * * ? *` ![23383d0055ee3d585f29501206eae990](https://user-images.githubusercontent.com/65161474/273367007-b35bcda6-51c3-4a2f-bb0f-bf355e58628a.png)
> 
> **After stopping, all tasks will be affected and an error will be reported as task instance is null or host is null.**
> 
> After stopping woker group info: ![9b4d332c44a6e62b7ca0854e98456d12](https://user-images.githubusercontent.com/65161474/273366917-aefc0176-213e-416d-b7e4-00ac23b161f9.png)
> 
> After stopping task execution status: ![b6582c94c541f103d7d43f14b9ec55ab](https://user-images.githubusercontent.com/65161474/273366920-90e4114c-7589-48a0-9912-e0ee278e4acb.png) ![5e80093fa06d528d3b5303f2b0e5fa69](https://user-images.githubusercontent.com/65161474/273366923-dac2288b-aaac-4e55-b9a0-489031da3cad.png) ![91f4f3c91f706e2cc5f750a1b482c496](https://user-images.githubusercontent.com/65161474/273366929-15f3e7f5-3d35-49cc-a65b-871050a85382.png) ![576601d98be9c6127e3bd64a1820a0b7](https://user-images.githubusercontent.com/65161474/273366931-14466014-bfab-46fb-9a6b-c1f9258cdc59.png)
> 
> error logs message： ![98e57f541dc77e1eabe63996bc65c22a](https://user-images.githubusercontent.com/65161474/273366951-78b647cc-08b0-4e63-805a-980fe828460e.png)
> 
> After starting the stopped worker, the task resumes execution. A large number of backlogged tasks are resuming execution, which may cause the cluster to be in a high load state and lead to the downtime of other services in the cluster. This is very dangerous
> 
> I don't quite understand why the node downtime of the '算法集群' worker group affects the tasks of other worker group nodes

@kezhenyang163 
From the steps of replication, it can be seen that when the nodes corresponding to my "算法集群" workgroup were closed, the tasks of the "大数据集群" and "default" workgroups were also affected and could not work properly. I think this is very unreasonable, as one of the executor nodes goes down, causing all nodes in the current system to be affected. Do you think it's reasonable?

**Comment by yihao-tcf** [comment] 2023-10-27 01:15
@kezhenyang163 
I believe that if the node corresponding to the "算法集群" workgroup goes down, it should affect the tasks of its corresponding workgroup. And it will not affect the working groups of other normal worker nodes. If a single node goes down and all tasks cannot run, then I think it will deviate from the "High Performance Workflow" described by Dolphinscheduler

**Closed as not planned** 2023-10-27 02:18 UTC
Labels: bug, help wanted

**Comment by touchhuang** [comment] 2023-10-27 02:22
@kezhenyang163 This may not be a bug, but it can indeed be troublesome, especially when multiple teams are collaborating.

**Comment by chenshuai1995** [comment] 2024-01-13 23:35
mark
