### ISSUE TITLE
[Bug] [TASK-SQL] java.lang.NullPointerException

### ISSUE THREAD

**Issue by Data-bytes305** [apache/dolphinscheduler#7482] opened 2021-12-18 08:50 UTC
version: 2.0.1

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[LOG-PATH]: /home/dolphinscheduler201/logs/3889265280992_1/3988/3254.log, [HOST]:  168.30.16.99
[INFO] 2021-12-18 16:35:58.617  - [taskAppId=TASK-3889265280992_1-3988-3254]:[121] - Full sql parameters: SqlParameters{type='ORACLE', datasource=2, sql='select 1 as a from dual', sqlType=0, sendEmail=true, displayRows=10, limit=0, udfs='', showType='null', connParams='', groupId='2', title='测试', preStatements=[select 1 from dual], postStatements=[select 1 from dual]}
[INFO] 2021-12-18 16:35:58.622  - [taskAppId=TASK-3889265280992_1-3988-3254]:[122] - sql type : ORACLE, datasource : 2, sql : select 1 as a from dual , localParams : [],udfs : ,showType : null,connParams : ,varPool : [] ,query max result limit  0
[INFO] 2021-12-18 16:35:58.625  - [taskAppId=TASK-3889265280992_1-3988-3254]:[483] - SQL title : 测试
[INFO] 2021-12-18 16:35:58.627  - [taskAppId=TASK-3889265280992_1-3988-3254]:[450] - after replace sql , preparing : select 1 as a from dual
[INFO] 2021-12-18 16:35:58.628  - [taskAppId=TASK-3889265280992_1-3988-3254]:[459] - Sql Params are replaced sql , parameters:
[INFO] 2021-12-18 16:35:58.629  - [taskAppId=TASK-3889265280992_1-3988-3254]:[483] - SQL title : 测试
[INFO] 2021-12-18 16:35:58.630  - [taskAppId=TASK-3889265280992_1-3988-3254]:[450] - after replace sql , preparing : select 1 from dual
[INFO] 2021-12-18 16:35:58.630  - [taskAppId=TASK-3889265280992_1-3988-3254]:[459] - Sql Params are replaced sql , parameters:
[INFO] 2021-12-18 16:35:58.631  - [taskAppId=TASK-3889265280992_1-3988-3254]:[483] - SQL title : 测试
[INFO] 2021-12-18 16:35:58.632  - [taskAppId=TASK-3889265280992_1-3988-3254]:[450] - after replace sql , preparing : select 1 from dual
[INFO] 2021-12-18 16:35:58.632  - [taskAppId=TASK-3889265280992_1-3988-3254]:[459] - Sql Params are replaced sql , parameters:
[INFO] 2021-12-18 16:35:58.632  - [taskAppId=TASK-3889265280992_1-3988-3254]:[529] - can't find udf function resource
[ERROR] 2021-12-18 16:35:58.637  - [taskAppId=TASK-3889265280992_1-3988-3254]:[212] - execute sql error: null
[ERROR] 2021-12-18 16:35:58.637  - [taskAppId=TASK-3889265280992_1-3988-3254]:[163] - sql task error: java.lang.NullPointerException

### What you expected to happen

success

### How to reproduce

如截图。

![image](https://user-images.githubusercontent.com/83893570/146635366-1c3c5f3b-06fd-496f-ae38-cf85d5dff388.png)

### Version

2.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment] 2021-12-19 02:33
This is a null pointer caused by sending mail, which has been fixed in version 2.0.1.

**Comment by zhuangchong** [comment] 2021-12-19 02:34
I will close this issue first, if you have any questions, you can continue to open this isssue

**Closed as completed by zhuangchong** 2021-12-19 02:34 UTC
Labels: bug, Waiting for reply
