### ISSUE TITLE
[Bug][Master] Worker resources are exhausted and cause downtime

### ISSUE THREAD

**Issue by vinnielhj** [apache/dolphinscheduler#8951] opened 2022-03-17 03:26 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After I upgraded from version 1.3.8 to 2.0.5, worker resources were exhausted due to too many tasks submitted by users。

### Use case

I looked through the source code and saw that in MasterConfig 1.3.8, there is a parameter masterExecTaskNum with a value of 20, that is, only 20 tasks can be submitted to the worker for execution at the same time. After upgrading to 2.0.5, although this parameter exists, it is not used. The master will rudely submit tasks to the workers for execution. I don't understand why it is designed this way.

This problem is fatal in production. I think the number of tasks running at the same time should be controlled, like version 1.3.8, to ensure that the pressure on the workers is not too high, even at the tenant level (ie each tenant can run at most N jobs at the same time) 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinnielhj** [comment] 2022-03-17 03:28
@caishunfeng @lenboo

**Comment by SbloodyS** [comment] 2022-03-17 03:39
Worker thread was controlled by ```worker.exec.threads``` in ```worker.properties```.

**Comment by caishunfeng** [comment] 2022-03-17 06:03
It is not a bug, and you can solve as @SbloodyS said. I will close this issue. 
BTW, this issue is not a feature, I change the title.

**Closed as completed by caishunfeng** 2022-03-17 06:03 UTC
Labels: bug
