### ISSUE TITLE
[Bug] [Alert] Users cannot select alarm groups when triggering / scheduling workflows

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#11249] opened 2022-08-02 05:52 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* After creating an ordinary user and alert groups with admin, I log out and re-login with the new user. Then when triggering / scheduling the workflows, there are no alert groups to select from.

![image](https://user-images.githubusercontent.com/34905992/182301500-87875b92-05a3-43a6-9655-a4cc279db4f9.png)

* I haven't found the error logs yet. Will follow up with error logs later.

### What you expected to happen

* Users should be able to choose alert groups when triggering / scheduling workflows.

### How to reproduce

* Already described in the `What happened` section.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricGao888** [comment] 2022-08-02 12:30
Seems we have the same situation with `Environment`:
![image](https://user-images.githubusercontent.com/34905992/182375015-f2627e84-ac57-4151-9d16-5a6362b47621.png)

**Comment by zhongjiajie** [comment] 2022-08-02 12:30
Hi @EricGao888 I can select the exists alert group in branch 3.0.0-prepare
<img width="2997" alt="image" src="https://user-images.githubusercontent.com/15820530/182375158-fc6ec378-c190-411b-b785-46607b79b1cc.png">

**Comment by EricGao888** [comment] 2022-08-02 12:32
> Hi @EricGao888 I can select the exists alert group in branch 3.0.0-prepare <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182375158-fc6ec378-c190-411b-b785-46607b79b1cc.png">

Looks like a bug on dev. If there's no such thing on 3.0.0-prepare, we may change the milestone to 3.1.0 or something else. WDYT @zhongjiajie @SbloodyS

**Comment by zhongjiajie** [comment] 2022-08-02 12:37
Oh, I find out it exists in workflow definition page instead of runing workflow dialog
<img width="3008" alt="image" src="https://user-images.githubusercontent.com/15820530/182376366-b39f89ec-36da-447d-ad89-c545cbce4300.png">

**Comment by zhongjiajie** [comment] 2022-08-02 12:41
@songjianet @Amy0104 @devosend I find out backend return the right entry, could you please take a look the frontend code?

**Comment by zhongjiajie** [comment] 2022-08-02 12:54
I re-test it, and find there are two error places
1. workflow definition -> Edit task -> select environment name
<img width="3008" alt="image" src="https://user-images.githubusercontent.com/15820530/182379393-bd511270-9071-40c1-a45f-2375e88f2288.png">

2. workflow definition -> mark workflow online -> trigger -> select environment name
<img width="3005" alt="image" src="https://user-images.githubusercontent.com/15820530/182379566-0be55b4d-d79a-49bc-b180-3442c7cb283b.png">

**Comment by Amy0104** [comment] 2022-08-03 05:43
> I re-test it, and find there are two error places
> 
> 1. workflow definition -> Edit task -> select environment name
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182379393-bd511270-9071-40c1-a45f-2375e88f2288.png">
> 
> 2. workflow definition -> mark workflow online -> trigger -> select environment name
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182379566-0be55b4d-d79a-49bc-b180-3442c7cb283b.png">

Have you selected a worker group for the environment? If not, the worker group of the environment list from the back end should be set to default not empty.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/97265214/182533679-cb72ee60-091b-4092-b58c-7e0b48804332.png">
@zhongjiajie pls cc.

**Comment by zhongjiajie** [comment] 2022-08-03 06:06
> > I re-test it, and find there are two error places
> > 
> > 1. workflow definition -> Edit task -> select environment name
> > 
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182379393-bd511270-9071-40c1-a45f-2375e88f2288.png">
> > 
> > 2. workflow definition -> mark workflow online -> trigger -> select environment name
> > 
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182379566-0be55b4d-d79a-49bc-b180-3442c7cb283b.png">
> 
> Have you selected a worker group for the environment? If not, the worker group of the environment list from the back end should be set to default not empty. <img alt="image" width="447" src="https://user-images.githubusercontent.com/97265214/182533679-cb72ee60-091b-4092-b58c-7e0b48804332.png"> @zhongjiajie pls cc.

Yesh, you are right I forget to connect the environment to workgroup, when I connect them then it work correctly, thanks for your clarification 👍

**Comment by zhongjiajie** [comment] 2022-08-03 06:06
cc @EricGao888

**Comment by EricGao888** [comment] 2022-08-03 06:12
> > I re-test it, and find there are two error places
> > 
> > 1. workflow definition -> Edit task -> select environment name
> > 
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182379393-bd511270-9071-40c1-a45f-2375e88f2288.png">
> > 
> > 2. workflow definition -> mark workflow online -> trigger -> select environment name
> > 
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/15820530/182379566-0be55b4d-d79a-49bc-b180-3442c7cb283b.png">
> 
> Have you selected a worker group for the environment? If not, the worker group of the environment list from the back end should be set to default not empty. <img alt="image" width="447" src="https://user-images.githubusercontent.com/97265214/182533679-cb72ee60-091b-4092-b58c-7e0b48804332.png"> @zhongjiajie pls cc.

@Amy0104 @zhongjiajie Thanks for the clarification. `Environments` works for me after associating it with `worker group`. My bad and I think I need to reread the docs : ). BTW, I still have the issue with `alarm groups`, do I miss anything here?

**Comment by zhongjiajie** [comment] 2022-08-03 06:21
> @Amy0104 @zhongjiajie Thanks for the clarification. Environments works for me after associating it with worker group. My bad and I think I need to reread the docs : ). BTW, I still have the issue with alarm groups, do I miss anything here?

alarm groups work in my laptop, can you run `mvn clean` and then restart the server? @EricGao888

**Comment by EricGao888** [comment] 2022-08-03 06:39
> > @Amy0104 @zhongjiajie Thanks for the clarification. Environments works for me after associating it with worker group. My bad and I think I need to reread the docs : ). BTW, I still have the issue with alarm groups, do I miss anything here?
> 
> alarm groups work in my laptop, can you run `mvn clean` and then restart the server? @EricGao888

@zhongjiajie Sure, I'm going to double check this. BTW, are u testing the dev branch for alarm group or 3.0.0-prepare?

**Comment by zhongjiajie** [comment] 2022-08-03 06:43
I only test in branch `3.0.0-prepare`

**Comment by EricGao888** [comment] 2022-08-03 06:47
> I only test in branch `3.0.0-prepare`

@zhongjiajie It does exist on dev branch.

**Comment by EricGao888** [comment] 2022-08-03 07:05
> > I only test in branch `3.0.0-prepare`
> 
> @zhongjiajie It does exist on dev branch.

Just pulled the latest code of `dev` branch and retested it, the alarm group issue still exists. cc @zhongjiajie @SbloodyS @Amy0104

**Comment by Amy0104** [comment] 2022-08-03 07:20
> > > I only test in branch `3.0.0-prepare`
> > 
> > 
> > @zhongjiajie It does exist on dev branch.
> 
> Just pulled the latest code of `dev` branch and retested it, the alarm group issue still exists. cc @zhongjiajie @SbloodyS @Amy0104

I tested it on branch dev. It is working for me if I set a worker group to the environment. Could you provide the response of the environment list request when creating a task. @EricGao888

**Comment by EricGao888** [comment] 2022-08-03 07:23
> > > > I only test in branch `3.0.0-prepare`
> > > 
> > > 
> > > @zhongjiajie It does exist on dev branch.
> > 
> > 
> > Just pulled the latest code of `dev` branch and retested it, the alarm group issue still exists. cc @zhongjiajie @SbloodyS @Amy0104
> 
> I tested it on branch dev. It is working for me if I set a worker group to the environment. Could you provide the response of the environment list request when creating a task. @EricGao888

I mean `Alarm Group`. `Environments` works on dev branch for me, as I've mentioned above: https://github.com/apache/dolphinscheduler/issues/11249#issuecomment-1203526359

**Comment by EricGao888** [comment] 2022-08-03 07:25
`{
    "code": 0,
    "msg": "success",
    "data": {
        "processDefinition": {
            "id": 1,
            "code": 6410218857792,
            "name": "sda",
            "version": 1,
            "releaseState": "ONLINE",
            "projectCode": 6410216556480,
            "description": "",
            "globalParams": "[]",
            "globalParamList": [],
            "globalParamMap": {},
            "createTime": "2022-08-03 07:03:54",
            "updateTime": "2022-08-03 07:03:54",
            "flag": "YES",
            "userId": 2,
            "userName": null,
            "projectName": null,
            "locations": "[{\"taskCode\":6410217114432,\"x\":158,\"y\":73}]",
            "scheduleReleaseState": null,
            "timeout": 0,
            "tenantId": -1,
            "tenantCode": null,
            "modifyBy": null,
            "warningGroupId": 0,
            "executionType": "PARALLEL"
        },
        "processTaskRelationList": [
            {
                "id": 1,
                "name": "",
                "processDefinitionVersion": 1,
                "projectCode": 6410216556480,
                "processDefinitionCode": 6410218857792,
                "preTaskCode": 0,
                "preTaskVersion": 0,
                "postTaskCode": 6410217114432,
                "postTaskVersion": 1,
                "conditionType": "NONE",
                "conditionParams": {},
                "createTime": "2022-08-03 07:03:54",
                "updateTime": "2022-08-03 07:03:54",
                "operator": 2,
                "operateTime": "2022-08-03 07:03:54"
            }
        ],
        "taskDefinitionList": [
            {
                "id": 1,
                "code": 6410217114432,
                "name": "ts",
                "version": 1,
                "description": "",
                "projectCode": 6410216556480,
                "userId": 2,
                "taskType": "SHELL",
                "taskParams": {
                    "localParams": [],
                    "rawScript": "echo hello",
                    "resourceList": []
                },
                "taskParamList": [],
                "taskParamMap": null,
                "flag": "YES",
                "taskPriority": "MEDIUM",
                "userName": null,
                "projectName": null,
                "workerGroup": "default",
                "environmentCode": -1,
                "failRetryTimes": 0,
                "failRetryInterval": 1,
                "timeoutFlag": "CLOSE",
                "timeoutNotifyStrategy": null,
                "timeout": 0,
                "delayTime": 0,
                "resourceIds": "",
                "createTime": "2022-08-03 07:03:54",
                "updateTime": "2022-08-03 07:03:54",
                "modifyBy": null,
                "taskGroupId": 0,
                "taskGroupPriority": 0,
                "cpuQuota": -1,
                "memoryMax": -1,
                "operator": 2,
                "operateTime": "2022-08-03 07:03:54",
                "dependence": ""
            }
        ]
    },
    "failed": false,
    "success": true
}`

**Comment by Amy0104** [comment] 2022-08-03 09:42
> > > > > I only test in branch `3.0.0-prepare`
> > > > 
> > > > 
> > > > @zhongjiajie It does exist on dev branch.
> > > 
> > > 
> > > Just pulled the latest code of `dev` branch and retested it, the alarm group issue still exists. cc @zhongjiajie @SbloodyS @Amy0104
> > 
> > 
> > I tested it on branch dev. It is working for me if I set a worker group to the environment. Could you provide the response of the environment list request when creating a task. @EricGao888
> 
> I mean `Alarm Group`. `Environments` works on dev branch for me, as I've mentioned above: [#11249 (comment)](https://github.com/apache/dolphinscheduler/issues/11249#issuecomment-1203526359)

I got u, but the alarm group works for me on dev branch. Can you reproduce this? @zhongjiajie

**Comment by EricGao888** [comment] 2022-08-03 09:52
> > > > > > I only test in branch `3.0.0-prepare`
> > > > > 
> > > > > 
> > > > > @zhongjiajie It does exist on dev branch.
> > > > 
> > > > 
> > > > Just pulled the latest code of `dev` branch and retested it, the alarm group issue still exists. cc @zhongjiajie @SbloodyS @Amy0104
> > > 
> > > 
> > > I tested it on branch dev. It is working for me if I set a worker group to the environment. Could you provide the response of the environment list request when creating a task. @EricGao888
> > 
> > 
> > I mean `Alarm Group`. `Environments` works on dev branch for me, as I've mentioned above: [#11249 (comment)](https://github.com/apache/dolphinscheduler/issues/11249#issuecomment-1203526359)
> 
> I got u, but the alarm group works for me on dev branch. Can you reproduce this? @zhongjiajie

Hi @Amy0104 , may I ask which user you used for testing? If u choose admin, it works. But if u choose some ordinary user, it happens. Probably something related to user / permission.

**Comment by Amy0104** [comment] 2022-08-03 10:00
> > > > > > > I only test in branch `3.0.0-prepare`
> > > > > > 
> > > > > > 
> > > > > > @zhongjiajie It does exist on dev branch.
> > > > > 
> > > > > 
> > > > > Just pulled the latest code of `dev` branch and retested it, the alarm group issue still exists. cc @zhongjiajie @SbloodyS @Amy0104
> > > > 
> > > > 
> > > > I tested it on branch dev. It is working for me if I set a worker group to the environment. Could you provide the response of the environment list request when creating a task. @EricGao888
> > > 
> > > 
> > > I mean `Alarm Group`. `Environments` works on dev branch for me, as I've mentioned above: [#11249 (comment)](https://github.com/apache/dolphinscheduler/issues/11249#issuecomment-1203526359)
> > 
> > 
> > I got u, but the alarm group works for me on dev branch. Can you reproduce this? @zhongjiajie
> 
> Hi @Amy0104 , may I ask which user you used for testing? If u choose admin, it works. But if u choose some ordinary user, it happens. Probably something related to user / permission.

I created a alarm group with admin account, and then changed to a ordinary user.

**Comment by ruanwenjun** [comment] 2022-08-03 12:05
I cannot see the alerm group with ordinary user :)

**Comment by ruanwenjun** [comment] 2022-08-03 12:05
+1 
I cannot see the alerm group with ordinary user :)

**Comment by ruanwenjun** [comment] 2022-08-04 03:53
> +1
> I cannot see the alerm group with ordinary user :)

I find this is caused by the back-end has a authority logic when query AlertGroup.

**Comment by WangJPLeo** [comment] 2022-08-04 08:39
> > +1
> > I cannot see the alerm group with ordinary user :)
> 
> I find this is caused by the back-end has a authority logic when query AlertGroup.

Yes, when a non-Admin user queries an AlertGroup, the condition is whether it is created by the current user. I will check the data query logic of other resources and submit a PR. A reasonable form should be able to authorize all data resources in the system, and Now the unified management of permissions has been extracted in the system.

**Comment by ruanwenjun** [comment] 2022-08-04 15:07
This should be fixed by #11301

**Closed as completed by ruanwenjun** 2022-08-04 15:07 UTC
Labels: bug, backend
