### ISSUE TITLE
[Bug] [workflow parameter] The workflow which pass parameter can't start 

### ISSUE THREAD

**Issue by ArkURL** [apache/dolphinscheduler#16117] opened 2024-06-05 09:32 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I follow the tutorial and try to pass parameter through the same workflow. and i found after configure it, the workflow can't be started. the workflow even not shown in "workflow instance" tab. but another workflow not pass parameter through workflow can start normally.

env: 
jdk1.8
dolphinscheduler 3.2.x
postgresql
zookeeper 3.7.x
os: centos 7

### What you expected to happen

the workflow which pass parameter through can start successfully.

### How to reproduce

follow the tutorial with the shell part:
https://dolphinscheduler.apache.org/zh-cn/docs/3.2.1/guide/parameter/context

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment] 2024-06-05 15:53
Is there any error log in the master server? You can find the error message in the error command.

**Comment by ArkURL** [comment] 2024-06-06 07:02
> Is there any error log in the master server? You can find the error message in the error command.

no, there is no workflow instance run log which pass parameter between nodes.
for example:
![image](https://github.com/apache/dolphinscheduler/assets/56484166/d30e6525-fba9-454d-9c52-c1e7c15bddcb)
the red workflow pass parameter through node but blue workflow not pass parameter, and only blue workflow can start and have workflow instance log when red workflow can't start.
![image](https://github.com/apache/dolphinscheduler/assets/56484166/049858fe-388c-4071-958c-d509bd27dd54)

Or can i find detail log in disk? I deploy the service with cluster in vitural machines.

**Comment by ruanwenjun** [comment] 2024-06-06 08:20
> > Is there any error log in the master server? You can find the error message in the error command.
> 
> no, there is no workflow instance run log which pass parameter between nodes. for example: ![image](https://private-user-images.githubusercontent.com/56484166/337154863-d30e6525-fba9-454d-9c52-c1e7c15bddcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjIyNzcsIm5iZiI6MTcxNzY2MTk3NywicGF0aCI6Ii81NjQ4NDE2Ni8zMzcxNTQ4NjMtZDMwZTY1MjUtZmJhOS00NTRkLTljNTItYzFlN2MxNWJkZGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA4MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjhiYzNlMTcxZDNlN2UyNWUzYTZjOTkzMTU4MTQ4NmMyZjY3ODQwM2Y2NGQ1MTRlZTgwMDgxNzkwYzFmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejM3nJ8TTXBbZWeBVKZ2G1sNpyjxbzJ2ZkTgmTqTiCs) the red workflow pass parameter through node but blue workflow not pass parameter, and only blue workflow can start and have workflow instance log when red workflow can't start. ![image](https://private-user-images.githubusercontent.com/56484166/337155353-049858fe-388c-4071-958c-d509bd27dd54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjIyNzcsIm5iZiI6MTcxNzY2MTk3NywicGF0aCI6Ii81NjQ4NDE2Ni8zMzcxNTUzNTMtMDQ5ODU4ZmUtMzg4Yy00MDcxLTk1OGMtZDUwOWJkMjdkZDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA4MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNTM4MjMzMmEwMjMwODViNGMxNGZlYmVhZGM2MzE1ZThhNDVmYWIwNDNiMmU2ZjM1N2JlYmY2NDVhODgzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z7p6QcLZWoAdeEKHhSGUA11WT0JU7hhOwuq_Md12dLA)
> 
> Or can i find detail log in disk? I deploy the service with cluster in vitural machines.

This may caused by parse parameter error, you can find the log detail on master.log

**Comment by ArkURL** [comment] 2024-06-06 09:04
> > > Is there any error log in the master server? You can find the error message in the error command.
> > 
> > 
> > no, there is no workflow instance run log which pass parameter between nodes. for example: ![image](https://private-user-images.githubusercontent.com/56484166/337154863-d30e6525-fba9-454d-9c52-c1e7c15bddcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjIyNzcsIm5iZiI6MTcxNzY2MTk3NywicGF0aCI6Ii81NjQ4NDE2Ni8zMzcxNTQ4NjMtZDMwZTY1MjUtZmJhOS00NTRkLTljNTItYzFlN2MxNWJkZGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA4MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjhiYzNlMTcxZDNlN2UyNWUzYTZjOTkzMTU4MTQ4NmMyZjY3ODQwM2Y2NGQ1MTRlZTgwMDgxNzkwYzFmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejM3nJ8TTXBbZWeBVKZ2G1sNpyjxbzJ2ZkTgmTqTiCs) the red workflow pass parameter through node but blue workflow not pass parameter, and only blue workflow can start and have workflow instance log when red workflow can't start. ![image](https://private-user-images.githubusercontent.com/56484166/337155353-049858fe-388c-4071-958c-d509bd27dd54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjIyNzcsIm5iZiI6MTcxNzY2MTk3NywicGF0aCI6Ii81NjQ4NDE2Ni8zMzcxNTUzNTMtMDQ5ODU4ZmUtMzg4Yy00MDcxLTk1OGMtZDUwOWJkMjdkZDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA4MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNTM4MjMzMmEwMjMwODViNGMxNGZlYmVhZGM2MzE1ZThhNDVmYWIwNDNiMmU2ZjM1N2JlYmY2NDVhODgzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z7p6QcLZWoAdeEKHhSGUA11WT0JU7hhOwuq_Md12dLA)
> > Or can i find detail log in disk? I deploy the service with cluster in vitural machines.
> 
> This may caused by parse parameter error, you can find the log detail on master.log

found error log in master node as below:
[WI-0][TI-0] - [INFO] 2024-06-06 16:49:29.750 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-06-06 16:49:31.652 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[187] - Master schedule bootstrap loop command success, fetch command size: 1, cost: 2ms, current slot: 0, total slot size: 1
[WI-0][TI-0] - [ERROR] 2024-06-06 16:49:31.661 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[156] - Master handle command 34 error 
org.apache.dolphinscheduler.server.master.exception.WorkflowCreateException: Create WorkflowExecuteRunnable failed
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnableFactory.createWorkflowExecuteRunnable(WorkflowExecuteRunnableFactory.java:98)
	at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap.lambda$run$0(MasterSchedulerBootstrap.java:139)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:676)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:264)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:785)
	at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerBootstrap.run(MasterSchedulerBootstrap.java:136)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.dolphinscheduler.plugin.task.api.model.Property.getValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.setGlobalParamIfCommanded(ProcessServiceImpl.java:604)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.generateNewProcessInstance(ProcessServiceImpl.java:561)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.constructProcessInstance(ProcessServiceImpl.java:707)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.handleCommand(ProcessServiceImpl.java:291)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$FastClassBySpringCGLIB$$9d3e18f9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$EnhancerBySpringCGLIB$$1cd56db1.handleCommand(<generated>)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteContextFactory.createWorkflowInstance(WorkflowExecuteContextFactory.java:81)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteContextFactory.createWorkflowExecuteRunnableContext(WorkflowExecuteContextFactory.java:56)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnableFactory.createWorkflowExecuteRunnable(WorkflowExecuteRunnableFactory.java:83)
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-06-06 16:49:34.812 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-06-06 16:49:39.872 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-06-06 16:49:44.922 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms


looks like java problem

**Comment by ruanwenjun** [comment] 2024-06-17 13:53
@ArkURL This should already been fixed by https://github.com/apache/dolphinscheduler/pull/15677

<img width="585" alt="image" src="https://github.com/apache/dolphinscheduler/assets/22415594/a70e772c-6891-401d-b90c-6a18d80b0d82">

**Comment by ruanwenjun** [comment] 2024-06-23 00:41
Duplicated with https://github.com/apache/dolphinscheduler/issues/15676

**Closed as completed by ruanwenjun** 2024-06-23 00:41 UTC
Labels: bug, duplicate, need more information
